package importer

const (
	sfRun  = "/runs[]"
	sfRule = sfRun + "/tool/driver/rules[]"
	sfRes  = sfRun + "/results[]"
	sfLoc  = sfRes + "/locations[]"
)

var _ = registerSpec(Spec{
	Format:        FormatSARIF,
	Title:         "SARIF 2.1.0",
	SourceVersion: "SARIF 2.1.0 (OASIS) as written by CodeQL, semgrep, trivy, gitleaks, betterleaks and other static analysis tools",
	Rules: []string{
		"The conversion is the module's FromSARIF (sarif.go); the importer adds the input limits and chooses the asset.",
		"Asset: Options.Repository (a receiver sets it from a verified identity); else the first repository a run names in versionControlProvenance (repositoryUri without user info, branch, revisionId); else Options.DefaultAsset or an unclassified asset named after the tool, with an issue.",
		"Severity: the security-severity score (result, then rule), else the result level, else the rule's default level, else medium. Type: the rule's tags, a CVE/GHSA rule id, else the tool name. Options.ToolType (sast, sca, secret, iac, web3), when set, decides the type and the tool capabilities instead.",
		"A secret scanner's region snippet is masked (ctis.MaskSecretMatch), and the raw value and each secret-looking word of it are masked in every other field: title, description, message, properties, tags and fingerprints.",
		"Fingerprint: the result's fingerprints entry with the lowest key (hashed above 64 characters); partialFingerprints pass through.",
	},
	Fields: []Field{
		{Path: "/$schema", Target: Container},
		{Path: "/version", Target: "format check (only 2.1.0 is read)"},
		{Path: "/runs", Target: Container},
		{Path: sfRun, Target: Container},
		{Path: sfRun + "/tool", Target: Container},
		{Path: sfRun + "/tool/driver", Target: Container},
		{Path: sfRun + "/tool/driver/name", Target: "tool.name, findings[].properties.sarif_tool (several runs)"},
		{Path: sfRun + "/tool/driver/version", Target: "tool.version"},
		{Path: sfRun + "/tool/driver/semanticVersion", Target: "tool.version (when no version)"},
		{Path: sfRun + "/tool/driver/informationUri", Target: "tool.info_url"},
		{Path: sfRun + "/tool/driver/fullName", Ignored: "display name; name is kept"},
		{Path: sfRun + "/tool/driver/organization", Ignored: "the tool vendor's name; not a finding property"},
		{Path: sfRun + "/tool/driver/rules", Target: Container},
		{Path: sfRule, Target: "the rule of each result"},
		{Path: sfRule + "/id", Target: "findings[].rule_id (rule lookup)"},
		{Path: sfRule + "/name", Target: "findings[].rule_name"},
		{Path: sfRule + "/shortDescription", Target: Container},
		{Path: sfRule + "/shortDescription/text", Target: "findings[].description, title (when the result has no message)"},
		{Path: sfRule + "/fullDescription", Ignored: "long rule text; the short description is kept"},
		{Path: sfRule + "/fullDescription/text", Ignored: "long rule text; the short description is kept"},
		{Path: sfRule + "/help", Ignored: "rule help text (documentation of the check, same for every finding)"},
		{Path: sfRule + "/help/**", Ignored: "rule help text (documentation of the check, same for every finding)"},
		{Path: sfRule + "/helpUri", Target: "findings[].references"},
		{Path: sfRule + "/defaultConfiguration", Target: Container},
		{Path: sfRule + "/defaultConfiguration/level", Target: "findings[].severity (when the result has no level)"},
		{Path: sfRule + "/defaultConfiguration/enabled", Ignored: "tool configuration"},
		{Path: sfRule + "/properties", Target: Container},
		{Path: sfRule + "/properties/tags", Target: "findings[].tags, type, vulnerability.cwe_ids, owasp_ids"},
		{Path: sfRule + "/properties/tags[]", Target: "findings[].tags, type, vulnerability.cwe_ids, owasp_ids"},
		{Path: sfRule + "/properties/precision", Target: "findings[].confidence"},
		{Path: sfRule + "/properties/security-severity", Target: "findings[].severity"},
		{Path: sfRule + "/properties/cwe", Target: "findings[].vulnerability.cwe_ids"},
		{Path: sfRule + "/properties/cwe[]", Target: "findings[].vulnerability.cwe_ids"},
		{Path: sfRule + "/properties/owasp", Target: "findings[].vulnerability.owasp_ids"},
		{Path: sfRule + "/properties/owasp[]", Target: "findings[].vulnerability.owasp_ids"},
		{Path: sfRule + "/properties/*", Ignored: "other rule properties (CodeQL id, kind, name, description, problem.severity): duplicates of rule members or tool internals"},
		{Path: sfRun + "/results", Target: Container},
		{Path: sfRes, Target: "findings[]"},
		{Path: sfRes + "/ruleId", Target: "findings[].rule_id"},
		{Path: sfRes + "/ruleIndex", Target: "rule lookup"},
		{Path: sfRes + "/rule", Target: Container},
		{Path: sfRes + "/rule/id", Target: "findings[].rule_id (when no ruleId)"},
		{Path: sfRes + "/rule/index", Target: "rule lookup"},
		{Path: sfRes + "/level", Target: "findings[].severity"},
		{Path: sfRes + "/kind", Target: "findings[].kind"},
		{Path: sfRes + "/baselineState", Target: "findings[].baseline_state"},
		{Path: sfRes + "/message", Target: Container},
		{Path: sfRes + "/message/text", Target: "findings[].title (secrets masked)"},
		{Path: sfRes + "/locations", Target: Container},
		{Path: sfLoc, Target: "findings[].location (the first location)"},
		{Path: sfLoc + "/physicalLocation", Target: Container},
		{Path: sfLoc + "/physicalLocation/artifactLocation", Target: Container},
		{Path: sfLoc + "/physicalLocation/artifactLocation/uri", Target: "findings[].location.path"},
		{Path: sfLoc + "/physicalLocation/artifactLocation/uriBaseId", Ignored: "base of a relative uri on the scanning machine; the relative path is kept"},
		{Path: sfLoc + "/physicalLocation/artifactLocation/index", Ignored: "index into run.artifacts; the uri is kept"},
		{Path: sfLoc + "/physicalLocation/region", Target: Container},
		{Path: sfLoc + "/physicalLocation/region/startLine", Target: "findings[].location.start_line"},
		{Path: sfLoc + "/physicalLocation/region/endLine", Target: "findings[].location.end_line"},
		{Path: sfLoc + "/physicalLocation/region/startColumn", Target: "findings[].location.start_column"},
		{Path: sfLoc + "/physicalLocation/region/endColumn", Target: "findings[].location.end_column"},
		{Path: sfLoc + "/physicalLocation/region/snippet", Target: Container},
		{Path: sfLoc + "/physicalLocation/region/snippet/text", Target: "findings[].location.snippet (masked for secret scanners)"},
		{Path: sfLoc + "/logicalLocations", Target: Container},
		{Path: sfLoc + "/logicalLocations[]", Target: Container},
		{Path: sfLoc + "/logicalLocations[]/name", Target: "findings[].location.logical_location.name"},
		{Path: sfLoc + "/logicalLocations[]/fullyQualifiedName", Target: "findings[].location.logical_location.fully_qualified_name"},
		{Path: sfLoc + "/logicalLocations[]/kind", Target: "findings[].location.logical_location.kind"},
		{Path: sfRes + "/fingerprints", Target: Container},
		{Path: sfRes + "/fingerprints/*", Target: "findings[].fingerprint (the lowest key)"},
		{Path: sfRes + "/partialFingerprints", Target: Container},
		{Path: sfRes + "/partialFingerprints/*", Target: "findings[].partial_fingerprints"},
		{Path: sfRes + "/correlationGuid", Target: "findings[].correlation_id"},
		{Path: sfRes + "/suppressions", Target: Container},
		{Path: sfRes + "/suppressions[]", Target: "findings[].suppression, status"},
		{Path: sfRes + "/suppressions[]/kind", Target: "findings[].suppression.kind"},
		{Path: sfRes + "/suppressions[]/status", Target: "findings[].suppression.status, status"},
		{Path: sfRes + "/suppressions[]/justification", Target: "findings[].suppression.justification"},
		{Path: sfRes + "/webRequest", Target: "findings[].evidence_items[http_exchange].http.request (capped, sensitive values marked)"},
		{Path: sfRes + "/webRequest/protocol", Target: "findings[].evidence_items[].http.request.http_version"},
		{Path: sfRes + "/webRequest/version", Target: "findings[].evidence_items[].http.request.http_version"},
		{Path: sfRes + "/webRequest/target", Target: "findings[].evidence_items[].http.request.url"},
		{Path: sfRes + "/webRequest/method", Target: "findings[].evidence_items[].http.request.method"},
		{Path: sfRes + "/webRequest/headers", Target: Container},
		{Path: sfRes + "/webRequest/headers/*", Target: "findings[].evidence_items[].http.request.headers[] (Authorization, Cookie and API-key values marked sensitive)"},
		{Path: sfRes + "/webRequest/body", Target: Container},
		{Path: sfRes + "/webRequest/body/text", Target: "findings[].evidence_items[].http.request.body"},
		{Path: sfRes + "/webRequest/body/binary", Target: "findings[].evidence_items[].http.request.body (base64)"},
		{Path: sfRes + "/webRequest/index", Ignored: "index into run.webRequests; the inline object is kept"},
		{Path: sfRes + "/webRequest/parameters", Ignored: "the request's parameters; the target URL and body hold them"},
		{Path: sfRes + "/webRequest/parameters/*", Ignored: "the request's parameters; the target URL and body hold them"},
		{Path: sfRes + "/webResponse", Target: "findings[].evidence_items[http_exchange].http.response (capped, sensitive values marked)"},
		{Path: sfRes + "/webResponse/protocol", Target: "findings[].evidence_items[].http.response.http_version"},
		{Path: sfRes + "/webResponse/version", Target: "findings[].evidence_items[].http.response.http_version"},
		{Path: sfRes + "/webResponse/statusCode", Target: "findings[].evidence_items[].http.response.status"},
		{Path: sfRes + "/webResponse/reasonPhrase", Target: "findings[].evidence_items[].http.response.reason"},
		{Path: sfRes + "/webResponse/headers", Target: Container},
		{Path: sfRes + "/webResponse/headers/*", Target: "findings[].evidence_items[].http.response.headers[] (Set-Cookie values marked sensitive)"},
		{Path: sfRes + "/webResponse/body", Target: Container},
		{Path: sfRes + "/webResponse/body/text", Target: "findings[].evidence_items[].http.response.body"},
		{Path: sfRes + "/webResponse/body/binary", Target: "findings[].evidence_items[].http.response.body (base64)"},
		{Path: sfRes + "/webResponse/noResponseReceived", Target: "findings[].evidence_items[].http.response (left out when true)"},
		{Path: sfRes + "/webResponse/index", Ignored: "index into run.webResponses; the inline object is kept"},
		{Path: sfRes + "/properties", Target: Container},
		{Path: sfRes + "/properties/tags", Target: "findings[].tags"},
		{Path: sfRes + "/properties/tags[]", Target: "findings[].tags"},
		{Path: sfRes + "/properties/tags[]/**", Ignored: "a tag that is not a string"},
		{Path: sfRes + "/properties/security-severity", Target: "findings[].severity"},
		{Path: sfRes + "/properties/*", Ignored: "other result properties (tool specific)"},
		{Path: sfRes + "/codeFlows", Ignored: "taint paths; the result's location is kept"},
		{Path: sfRes + "/codeFlows[]/**", Ignored: "taint paths; the result's location is kept"},
		{Path: sfRes + "/relatedLocations", Ignored: "secondary locations; the primary location is kept"},
		{Path: sfRes + "/relatedLocations[]/**", Ignored: "secondary locations; the primary location is kept"},
		{Path: sfRun + "/versionControlProvenance", Target: Container},
		{Path: sfRun + "/versionControlProvenance[]", Target: "assets[] (when no repository is given)"},
		{Path: sfRun + "/versionControlProvenance[]/repositoryUri", Target: "assets[].value (user info removed)"},
		{Path: sfRun + "/versionControlProvenance[]/revisionId", Target: "assets[].properties.commit_sha"},
		{Path: sfRun + "/versionControlProvenance[]/branch", Target: "assets[].properties.branch"},
		{Path: sfRun + "/invocations", Ignored: "how the tool ran (command line, environment, exit code): scan operation details, may hold paths and arguments of the build machine"},
		{Path: sfRun + "/invocations[]/**", Ignored: "how the tool ran: scan operation details"},
		{Path: sfRun + "/artifacts", Ignored: "the files the tool read; findings name their own file"},
		{Path: sfRun + "/artifacts[]/**", Ignored: "the files the tool read; findings name their own file"},
		{Path: sfRun + "/originalUriBaseIds", Ignored: "root paths of the scanning machine"},
		{Path: sfRun + "/originalUriBaseIds/**", Ignored: "root paths of the scanning machine"},
		{Path: sfRun + "/columnKind", Ignored: "column unit (UTF-16 or Unicode code points)"},
		{Path: sfRun + "/automationDetails", Ignored: "run category of a code-scanning upload"},
		{Path: sfRun + "/automationDetails/**", Ignored: "run category of a code-scanning upload"},
		{Path: sfRun + "/properties", Ignored: "run properties (tool specific)"},
		{Path: sfRun + "/properties/**", Ignored: "run properties (tool specific)"},
		{Path: sfRun + "/tool/extensions", Ignored: "tool plug-ins and query packs"},
		{Path: sfRun + "/tool/extensions/**", Ignored: "tool plug-ins and query packs"},
	},
})
