package importer

// cdxComponentFields are the rows of a component: the subject
// (/metadata/component) becomes the asset, every other component a
// dependency. Nested components fold to /components[] (cdxRewrite).
func cdxComponentFields() []Field {
	const s = "/metadata/component"
	const c = "/components[]"
	subjectOnly := "the subject keeps its identity (name, version, purl, cpe, type); its other details describe the product, not the scanned asset"
	return []Field{
		{Path: s, Target: "assets[] (the subject of the BOM)"},
		{Path: s + "/bom-ref", Target: "vulnerabilities[].affects[].ref resolution to the subject"},
		{Path: s + "/type", Target: "assets[].type (container; operating-system, device, firmware, platform: host; else repository), assets[].properties.component_type"},
		{Path: s + "/group", Target: "assets[].name (group/name)"},
		{Path: s + "/name", Target: "assets[].name, assets[].value (name@version when no purl)"},
		{Path: s + "/version", Target: "assets[].value, assets[].properties.version"},
		{Path: s + "/purl", Target: "assets[].value"},
		{Path: s + "/cpe", Target: "assets[].properties.cpe"},
		{Path: s + "/components", Target: Container},
		{Path: s + "/description", Ignored: subjectOnly},
		{Path: s + "/scope", Ignored: subjectOnly},
		{Path: s + "/hashes", Ignored: subjectOnly},
		{Path: s + "/hashes[]/**", Ignored: subjectOnly},
		{Path: s + "/licenses", Ignored: subjectOnly},
		{Path: s + "/licenses[]/**", Ignored: subjectOnly},
		{Path: s + "/supplier/**", Ignored: subjectOnly},
		{Path: s + "/publisher", Ignored: subjectOnly},
		{Path: s + "/properties", Ignored: subjectOnly},
		{Path: s + "/properties[]/**", Ignored: subjectOnly},
		{Path: s + "/externalReferences/**", Ignored: subjectOnly},
		{Path: s + "/author", Ignored: "a person's name"},
		{Path: s + "/authors/**", Ignored: "people's names and contacts"},
		{Path: s + "/manufacturer/**", Ignored: subjectOnly},
		{Path: s + "/copyright", Ignored: subjectOnly},

		{Path: c, Target: "dependencies[]"},
		{Path: c + "/bom-ref", Target: "dependencies[].id, vulnerabilities[].affects[].ref resolution"},
		{Path: c + "/type", Target: "dependencies[].type"},
		{Path: c + "/group", Target: "dependencies[].properties.group, findings[].vulnerability.package (group/name)"},
		{Path: c + "/name", Target: "dependencies[].name, findings[].vulnerability.package"},
		{Path: c + "/version", Target: "dependencies[].version, findings[].vulnerability.affected_version"},
		{Path: c + "/description", Target: "dependencies[].properties.description"},
		{Path: c + "/scope", Target: "dependencies[].properties.scope"},
		{Path: c + "/purl", Target: "dependencies[].purl, dependencies[].ecosystem (purl type), findings[].vulnerability.purl, ecosystem"},
		{Path: c + "/cpe", Target: "dependencies[].properties.cpe, findings[].vulnerability.cpe"},
		{Path: c + "/hashes", Target: Container},
		{Path: c + "/hashes[]", Target: Container},
		{Path: c + "/hashes[]/alg", Target: "dependencies[].properties.hash_<alg> (key)"},
		{Path: c + "/hashes[]/content", Target: "dependencies[].properties.hash_<alg>"},
		{Path: c + "/licenses", Target: Container},
		{Path: c + "/licenses[]", Target: Container},
		{Path: c + "/licenses[]/license", Target: Container},
		{Path: c + "/licenses[]/license/id", Target: "dependencies[].licenses"},
		{Path: c + "/licenses[]/license/name", Target: "dependencies[].licenses (when no id)"},
		{Path: c + "/licenses[]/license/url", Ignored: "license text location; the id or name is kept"},
		{Path: c + "/licenses[]/license/text/**", Ignored: "license text; the id or name is kept"},
		{Path: c + "/licenses[]/license/acknowledgement", Ignored: "declared or concluded; the license is kept either way"},
		{Path: c + "/licenses[]/expression", Target: "dependencies[].licenses"},
		{Path: c + "/supplier", Target: Container},
		{Path: c + "/supplier/name", Target: "dependencies[].properties.supplier"},
		{Path: c + "/supplier/url", Ignored: "supplier web site"},
		{Path: c + "/supplier/url[]", Ignored: "supplier web site"},
		{Path: c + "/supplier/contact[]/**", Ignored: "people's names, e-mail addresses and phone numbers"},
		{Path: c + "/supplier/contact", Ignored: "people's names, e-mail addresses and phone numbers"},
		{Path: c + "/publisher", Target: "dependencies[].properties.publisher"},
		{Path: c + "/author", Ignored: "a person's name"},
		{Path: c + "/authors/**", Ignored: "people's names and contacts"},
		{Path: c + "/manufacturer/**", Ignored: "manufacturer contact details"},
		{Path: c + "/copyright", Ignored: "copyright notice text"},
		{Path: c + "/properties", Target: Container},
		{Path: c + "/properties[]", Target: Container},
		{Path: c + "/properties[]/name", Target: "dependencies[].properties.property:<name> (key)"},
		{Path: c + "/properties[]/value", Target: "dependencies[].properties.property:<name>"},
		{Path: c + "/components", Target: Container},
		{Path: c + "/externalReferences", Ignored: "links to the project (VCS, web site, issue tracker); not a property of the installed component"},
		{Path: c + "/externalReferences[]/**", Ignored: "links to the project (VCS, web site, issue tracker); not a property of the installed component"},
		{Path: c + "/evidence/**", Ignored: "how the producer found the component (occurrences, call stacks); can hold build paths"},
		{Path: c + "/pedigree/**", Ignored: "ancestors and patches of the component; not imported"},
		{Path: c + "/swid/**", Ignored: "SWID tag; purl and cpe identify the component"},
		{Path: c + "/omniborId", Ignored: "artifact id; purl identifies the component"},
		{Path: c + "/omniborId[]", Ignored: "artifact id; purl identifies the component"},
		{Path: c + "/swhid", Ignored: "artifact id; purl identifies the component"},
		{Path: c + "/swhid[]", Ignored: "artifact id; purl identifies the component"},
		{Path: c + "/mime-type", Ignored: "file type of a file component"},
		{Path: c + "/modified", Ignored: "deprecated flag (use pedigree)"},
		{Path: c + "/tags", Ignored: "free-form labels of the producer"},
		{Path: c + "/tags[]", Ignored: "free-form labels of the producer"},
		{Path: c + "/releaseNotes/**", Ignored: "release notes text"},
		{Path: c + "/modelCard/**", Ignored: "machine-learning model card"},
		{Path: c + "/data/**", Ignored: "data set description"},
		{Path: c + "/cryptoProperties/**", Ignored: "cryptographic asset inventory (CBOM); not imported"},
		{Path: c + "/signature/**", Ignored: "signature of the component entry"},
	}
}

func cdxFields() []Field {
	const v = "/vulnerabilities[]"
	out := []Field{
		{Path: "/bomFormat", Target: "format detection (must be CycloneDX)"},
		{Path: "/$schema", Ignored: "schema location"},
		{Path: "/specVersion", Target: "metadata.properties.cyclonedx_spec_version"},
		{Path: "/serialNumber", Target: "metadata.properties.bom_serial_number, findings[].vex.source, vex[].vex.source"},
		{Path: "/version", Target: "metadata.properties.bom_version"},
		{Path: "/metadata", Target: Container},
		{Path: "/metadata/timestamp", Target: "metadata.properties.bom_timestamp"},
		{Path: "/metadata/tools/**", Ignored: "the tools that wrote the BOM"},
		{Path: "/metadata/tools[]/**", Ignored: "the tools that wrote the BOM"},
		{Path: "/metadata/authors", Ignored: "people's names and contacts"},
		{Path: "/metadata/authors[]/**", Ignored: "people's names and contacts"},
		{Path: "/metadata/manufacture/**", Ignored: "manufacturer contact details"},
		{Path: "/metadata/manufacturer/**", Ignored: "manufacturer contact details"},
		{Path: "/metadata/supplier/**", Ignored: "supplier contact details"},
		{Path: "/metadata/licenses/**", Ignored: "license of the BOM document itself"},
		{Path: "/metadata/properties/**", Ignored: "producer-specific properties of the BOM document"},
		{Path: "/metadata/lifecycles/**", Ignored: "product lifecycle phase the BOM was made in"},
		{Path: "/components", Target: Container},
	}
	out = append(out, cdxComponentFields()...)
	out = append(out,
		Field{Path: "/dependencies", Target: Container},
		Field{Path: "/dependencies[]", Target: Container},
		Field{Path: "/dependencies[]/ref", Target: "dependencies[] (the dependent); dependencies[].relationship (direct when the subject depends on it)"},
		Field{Path: "/dependencies[]/dependsOn", Target: Container},
		Field{Path: "/dependencies[]/dependsOn[]", Target: "dependencies[].depends_on (refs that name a component)"},
		Field{Path: "/dependencies[]/provides", Ignored: "specifications a component implements (CBOM)"},
		Field{Path: "/dependencies[]/provides[]", Ignored: "specifications a component implements (CBOM)"},

		Field{Path: "/vulnerabilities", Target: Container},
		Field{Path: v, Target: "findings[] (one per affected component of this BOM), vex[] (with an analysis)"},
		Field{Path: v + "/bom-ref", Target: "findings[].native.instance_id"},
		Field{Path: v + "/id", Target: "findings[].rule_id, native.vuln_id, vulnerability.ids, cve_id; vex[].vulnerability_ids"},
		Field{Path: v + "/source", Target: Container},
		Field{Path: v + "/source/name", Target: "findings[].vulnerability.data_source.name"},
		Field{Path: v + "/source/url", Target: "findings[].vulnerability.data_source.url, references"},
		Field{Path: v + "/references", Target: Container},
		Field{Path: v + "/references[]", Target: Container},
		Field{Path: v + "/references[]/id", Target: "findings[].vulnerability.ids; vex[].vulnerability_ids"},
		Field{Path: v + "/references[]/source", Target: Container},
		Field{Path: v + "/references[]/source/name", Target: "findings[].vulnerability.ids[].source (vendor ids)"},
		Field{Path: v + "/references[]/source/url", Ignored: "the id is kept; the database link is derived from it"},
		Field{Path: v + "/ratings", Target: Container},
		Field{Path: v + "/ratings[]", Target: "findings[].scores[]"},
		Field{Path: v + "/ratings[]/source", Target: Container},
		Field{Path: v + "/ratings[]/source/name", Target: "findings[].scores[].source"},
		Field{Path: v + "/ratings[]/source/url", Ignored: "the source name is kept"},
		Field{Path: v + "/ratings[]/score", Target: "findings[].scores[].value, vulnerability.cvss_score, severity (when no severity word)"},
		Field{Path: v + "/ratings[]/severity", Target: "findings[].severity (from the newest CVSS rating), native.severity, scores[].label"},
		Field{Path: v + "/ratings[]/method", Target: "findings[].scores[].system and version (CVSSv2, CVSSv3, CVSSv31, CVSSv4, SSVC; others vendor)"},
		Field{Path: v + "/ratings[]/vector", Target: "findings[].scores[].vector, vulnerability.cvss_vector"},
		Field{Path: v + "/ratings[]/justification", Target: "findings[].source_extra.rating_justification:<source>:<method>"},
		Field{Path: v + "/cwes", Target: Container},
		Field{Path: v + "/cwes[]", Target: "findings[].vulnerability.cwe_ids"},
		Field{Path: v + "/description", Target: "findings[].description, message"},
		Field{Path: v + "/detail", Target: "findings[].description"},
		Field{Path: v + "/recommendation", Target: "findings[].remediation.recommendation"},
		Field{Path: v + "/workaround", Target: "findings[].remediation.steps, solution_type workaround (when no recommendation)"},
		Field{Path: v + "/proofOfConcept/**", Ignored: "reproduction steps and exploit material; not copied into findings"},
		Field{Path: v + "/advisories", Target: Container},
		Field{Path: v + "/advisories[]", Target: "findings[].remediation.advisories"},
		Field{Path: v + "/advisories[]/title", Target: "findings[].remediation.advisories[].id"},
		Field{Path: v + "/advisories[]/url", Target: "findings[].remediation.advisories[].url, references"},
		Field{Path: v + "/created", Target: "findings[].source_extra.created"},
		Field{Path: v + "/published", Target: "findings[].vulnerability.published_at"},
		Field{Path: v + "/updated", Target: "findings[].vulnerability.modified_at"},
		Field{Path: v + "/rejected", Target: "findings[].source_extra.rejected"},
		Field{Path: v + "/credits/**", Ignored: "people and organizations credited; names and contacts"},
		Field{Path: v + "/tools/**", Ignored: "the tools that found the vulnerability"},
		Field{Path: v + "/tools[]/**", Ignored: "the tools that found the vulnerability"},
		Field{Path: v + "/analysis", Target: "findings[].vex, vex[]"},
		Field{Path: v + "/analysis/state", Target: "findings[].vex.status, vex[].vex.status; no finding for not_affected, resolved, resolved_with_pedigree, false_positive"},
		Field{Path: v + "/analysis/justification", Target: "findings[].vex.justification, native_justification"},
		Field{Path: v + "/analysis/response", Target: Container},
		Field{Path: v + "/analysis/response[]", Target: "findings[].source_extra.analysis_response"},
		Field{Path: v + "/analysis/detail", Target: "findings[].vex.statement"},
		Field{Path: v + "/analysis/firstIssued", Target: "findings[].vex.as_of (when no lastUpdated)"},
		Field{Path: v + "/analysis/lastUpdated", Target: "findings[].vex.as_of"},
		Field{Path: v + "/affects", Target: Container},
		Field{Path: v + "/affects[]", Target: "findings[] (one per affected component), vex[].products"},
		Field{Path: v + "/affects[]/ref", Target: "findings[].vulnerability.package/purl/affected_version (the component), vex[].products"},
		Field{Path: v + "/affects[]/versions", Target: Container},
		Field{Path: v + "/affects[]/versions[]", Target: "findings[].source_extra.affects_versions"},
		Field{Path: v + "/affects[]/versions[]/version", Target: "findings[].source_extra.affects_versions"},
		Field{Path: v + "/affects[]/versions[]/range", Target: "findings[].source_extra.affects_versions"},
		Field{Path: v + "/affects[]/versions[]/status", Target: "findings[].source_extra.affects_versions"},
		Field{Path: v + "/properties", Target: Container},
		Field{Path: v + "/properties[]", Target: Container},
		Field{Path: v + "/properties[]/name", Target: "findings[].source_extra.property:<name> (key)"},
		Field{Path: v + "/properties[]/value", Target: "findings[].source_extra.property:<name>"},

		Field{Path: "/services", Ignored: "services of the product (endpoints, data flows); not imported"},
		Field{Path: "/services[]/**", Ignored: "services of the product (endpoints, data flows); not imported"},
		Field{Path: "/externalReferences", Ignored: "links about the product"},
		Field{Path: "/externalReferences[]/**", Ignored: "links about the product"},
		Field{Path: "/compositions", Ignored: "completeness claims of the BOM"},
		Field{Path: "/compositions[]/**", Ignored: "completeness claims of the BOM"},
		Field{Path: "/annotations", Ignored: "comments by people; names and text"},
		Field{Path: "/annotations[]/**", Ignored: "comments by people; names and text"},
		Field{Path: "/formulation/**", Ignored: "how the product was built"},
		Field{Path: "/properties", Ignored: "producer-specific properties of the BOM document"},
		Field{Path: "/properties[]/**", Ignored: "producer-specific properties of the BOM document"},
		Field{Path: "/signature/**", Ignored: "signature of the BOM; verification is the uploader's concern"},
		Field{Path: "/definitions/**", Ignored: "standards definitions (CycloneDX 1.6 attestations)"},
		Field{Path: "/declarations/**", Ignored: "conformance declarations (CycloneDX 1.6 attestations)"},
	)
	return out
}

var _ = registerSpec(Spec{
	Format:        FormatCycloneDX,
	Title:         "CycloneDX JSON (SBOM, VDR, VEX)",
	SourceVersion: "CycloneDX 1.4, 1.5 and 1.6 JSON",
	Rules: []string{
		"The subject (metadata.component) is the asset: value is its purl, else name@version; type container for a container, host for an operating system, device, firmware or platform, else repository. Without a subject, an unclassified asset named after the serial number holds the components and findings, and an issue says so. A BOM without components or findings (a pure VEX) creates no asset.",
		"Every other component, at any nesting depth, is a dependency of the subject: id is its bom-ref (else purl, else name@version); a second component with a used bom-ref is skipped with an issue. depends_on keeps only refs that name a component; relationship is direct when the subject depends on it, indirect when the BOM has a dependency graph.",
		"One finding per vulnerability and affected component of this BOM (affects[].ref naming a component, or the subject). A ref that is a package URL outside the BOM is a VEX product but no finding.",
		"Severity: the severity word of the newest CVSS rating (else the first rating with one; a CVSS score without a word is banded 9/7/4/0.1); without any, medium with a note in source_extra. Every rating goes to scores (CVSSv2/v3/v31/v4 as cvss with version, SSVC as ssvc, others as vendor). The legacy cvss_* members take the newest CVSS rating.",
		"analysis maps through ctis.NormalizeVEXStatus and NormalizeVEXJustification. It becomes finding.vex and one VEX statement per vulnerability whose products are the affected components (purl, cpe, name, version). A not_affected analysis without a known justification or a detail is refused (issue). No finding is made for not_affected, resolved, resolved_with_pedigree and false_positive; they count as skipped.",
		"The VEX source is the BOM serial number.",
		"People's names and contacts (authors, credits, supplier contacts, annotations) are not read. Proof-of-concept material is not copied.",
	},
	Fields: cdxFields(),
})
