package importer

const ddF = "/findings[]"

var _ = registerSpec(Spec{
	Format:        FormatDefectDojo,
	Title:         "DefectDojo Generic Findings Import JSON",
	SourceVersion: "the Generic Findings Import JSON of DefectDojo 2.x (scan type \"Generic Findings Import\")",
	Rules: []string{
		"One finding per record and endpoint host; a record without endpoints is one finding on Options.DefaultAsset, else on an unclassified asset named after the tool (`<tool-name-slug>-import`).",
		"Endpoint hosts become domain or ip_address assets (id `host-<host>`); the endpoint port, protocol and URL go to the finding's network location and source_extra.endpoint.",
		"Severity: the label (Critical, High, Medium, Low, Info) through ctis.NormalizeNativeSeverity; native.severity keeps it.",
		"Status: the flags, in the order false_p, risk_accepted, out_of_scope, duplicate, is_mitigated, active=false (inactive), verified, active, give native.status; ctis.NormalizeNativeStatus maps it to the finding status and source state.",
		"vuln_id_from_tool is rule_id and native.vuln_id; unique_id_from_tool is native.instance_id. No fingerprint is set: the receiver keys findings.",
		"Values that are numbers or booleans in some exports and strings in others are read either way. A record that cannot be decoded is skipped with an issue at its line.",
	},
	Fields: []Field{
		{Path: "/name", Target: "tool.name"},
		{Path: "/type", Target: "metadata.properties.scan_type"},
		{Path: "/version", Target: "tool.version"},
		{Path: "/description", Target: "metadata.properties.description"},
		{Path: "/findings", Target: Container},
		{Path: ddF, Target: "findings[]"},
		{Path: ddF + "/title", Target: "findings[].title, rule_name"},
		{Path: ddF + "/description", Target: "findings[].description"},
		{Path: ddF + "/severity", Target: "findings[].severity, native.severity"},
		{Path: ddF + "/numerical_severity", Ignored: "derived from severity (S0-S4)"},
		{Path: ddF + "/severity_justification", Target: "findings[].source_extra.severity_justification"},
		{Path: ddF + "/mitigation", Target: "findings[].remediation.recommendation"},
		{Path: ddF + "/impact", Target: "findings[].source_extra.impact"},
		{Path: ddF + "/references", Target: "findings[].references (the URLs), source_extra.references (the text)"},
		{Path: ddF + "/steps_to_reproduce", Target: "findings[].source_extra.steps_to_reproduce"},
		{Path: ddF + "/date", Target: "findings[].first_seen_at, source_lifecycle.first_found"},
		{Path: ddF + "/publish_date", Target: "findings[].vulnerability.published_at"},
		{Path: ddF + "/cve", Target: "findings[].vulnerability.cve_id, cve_ids, ids[]"},
		{Path: ddF + "/cwe", Target: "findings[].vulnerability.cwe_id, cwe_ids"},
		{Path: ddF + "/vulnerability_ids", Target: Container},
		{Path: ddF + "/vulnerability_ids[]", Target: Container},
		{Path: ddF + "/vulnerability_ids[]/vulnerability_id", Target: "findings[].vulnerability.ids[] (cve, ghsa, osv or vendor)"},
		{Path: ddF + "/cvssv3", Target: "findings[].scores[] (cvss 3.x vector), vulnerability.cvss_vector"},
		{Path: ddF + "/cvssv3_score", Target: "findings[].scores[].value, vulnerability.cvss_score"},
		{Path: ddF + "/cvssv4", Target: "findings[].scores[] (cvss 4.0 vector)"},
		{Path: ddF + "/cvssv4_score", Target: "findings[].scores[].value (cvss 4.0)"},
		{Path: ddF + "/epss_score", Target: "findings[].scores[] (epss), vulnerability.epss_score"},
		{Path: ddF + "/epss_percentile", Target: "findings[].scores[] (epss_percentile), vulnerability.epss_percentile"},
		{Path: ddF + "/known_exploited", Target: "findings[].vulnerability.in_cisa_kev, exploit_available"},
		{Path: ddF + "/ransomware_used", Target: "findings[].source_extra.ransomware_used"},
		{Path: ddF + "/kev_date", Target: "findings[].source_extra.kev_date"},
		{Path: ddF + "/active", Target: "findings[].native.status, status, source_lifecycle.state"},
		{Path: ddF + "/verified", Target: "findings[].native.status, native.detection_type confirmed"},
		{Path: ddF + "/false_p", Target: "findings[].native.status, status false_positive"},
		{Path: ddF + "/duplicate", Target: "findings[].native.status, status suppressed"},
		{Path: ddF + "/out_of_scope", Target: "findings[].native.status, status suppressed"},
		{Path: ddF + "/risk_accepted", Target: "findings[].native.status, status accepted_risk"},
		{Path: ddF + "/is_mitigated", Target: "findings[].native.status, status resolved, source_lifecycle.state fixed"},
		{Path: ddF + "/mitigated", Target: "findings[].source_lifecycle.last_fixed, source_extra.mitigated"},
		{Path: ddF + "/under_review", Target: "findings[].source_extra.under_review"},
		{Path: ddF + "/file_path", Target: "findings[].location.path"},
		{Path: ddF + "/line", Target: "findings[].location.start_line"},
		{Path: ddF + "/sast_source_object", Target: "findings[].source_extra.sast_source_object"},
		{Path: ddF + "/sast_sink_object", Target: "findings[].source_extra.sast_sink_object"},
		{Path: ddF + "/sast_source_line", Target: "findings[].source_extra.sast_source_line"},
		{Path: ddF + "/sast_source_file_path", Target: "findings[].source_extra.sast_source_file_path"},
		{Path: ddF + "/component_name", Target: "findings[].vulnerability.package"},
		{Path: ddF + "/component_version", Target: "findings[].vulnerability.affected_version"},
		{Path: ddF + "/fix_available", Target: "findings[].remediation.fix_available"},
		{Path: ddF + "/fix_version", Target: "findings[].vulnerability.fixed_version, remediation.fix_available"},
		{Path: ddF + "/vuln_id_from_tool", Target: "findings[].rule_id, native.vuln_id"},
		{Path: ddF + "/unique_id_from_tool", Target: "findings[].native.instance_id"},
		{Path: ddF + "/endpoints", Target: Container},
		{Path: ddF + "/endpoints[]", Target: "assets[] (the host), findings[].network, source_extra.endpoint (a URL string is read too)"},
		{Path: ddF + "/endpoints[]/protocol", Target: "findings[].network.service, source_extra.endpoint"},
		{Path: ddF + "/endpoints[]/host", Target: "assets[].value, findings[].network.host"},
		{Path: ddF + "/endpoints[]/port", Target: "findings[].network.port"},
		{Path: ddF + "/endpoints[]/path", Target: "findings[].source_extra.endpoint"},
		{Path: ddF + "/endpoints[]/query", Target: "findings[].source_extra.endpoint"},
		{Path: ddF + "/endpoints[]/fragment", Target: "findings[].source_extra.endpoint"},
		{Path: ddF + "/endpoints[]/userinfo", Ignored: "credentials of the endpoint URL"},
		{Path: ddF + "/tags", Target: Container},
		{Path: ddF + "/tags[]", Target: "findings[].tags"},
		{Path: ddF + "/service", Target: "findings[].source_extra.service"},
		{Path: ddF + "/planned_remediation_date", Target: "findings[].source_extra.planned_remediation_date"},
		{Path: ddF + "/planned_remediation_version", Target: "findings[].source_extra.planned_remediation_version"},
		{Path: ddF + "/effort_for_fixing", Target: "findings[].remediation.effort"},
		{Path: ddF + "/static_finding", Target: "findings[].source_extra.static_finding"},
		{Path: ddF + "/dynamic_finding", Target: "findings[].source_extra.dynamic_finding"},
		{Path: ddF + "/payload", Target: "findings[].evidence"},
		{Path: ddF + "/param", Target: "findings[].source_extra.param"},
		{Path: ddF + "/nb_occurences", Target: "findings[].occurrence_count"}, //nolint:misspell // the source field is spelled this way
		{Path: ddF + "/hash_code", Ignored: "DefectDojo's own deduplication hash; the receiver keys findings itself"},
		{Path: ddF + "/files", Ignored: "attached files (base64 data); not imported"},
		{Path: ddF + "/files[]", Ignored: "attached files (base64 data); not imported"},
		{Path: ddF + "/files[]/**", Ignored: "attached files (base64 data); not imported"},
		{Path: ddF + "/reporter", Ignored: "the DefectDojo user who reported it (personal data)"},
		{Path: ddF + "/mitigated_by", Ignored: "the DefectDojo user who mitigated it (personal data)"},
	},
})
