package importer

var _ = registerSpec(Spec{
	Format:        FormatNuclei,
	Title:         "nuclei JSON lines",
	SourceVersion: "nuclei v3 -jsonl (one result per line) or -json-export (an array of the same objects)",
	Rules: []string{
		"One finding per result, on a domain or ip_address asset named by host, else matched-at, else ip (ids asset-1, asset-2, ... in order of first appearance). A result that names no host is skipped with an issue.",
		"Each line (or array element) is checked on its own: invalid JSON, a value over a limit or a wrong type skips that record with an issue at its line; the other records are imported.",
		"Raw HTTP requests and responses, the curl command and extracted values are never read: they can hold cookies, tokens and other data of the target.",
		"User info in matched-at is removed.",
	},
	Fields: []Field{
		{Path: "/template-id", Target: "findings[].rule_id, native.vuln_id"},
		{Path: "/template", Target: "findings[].source_extra.template_path"},
		{Path: "/template-path", Target: "findings[].source_extra.template_path"},
		{Path: "/template-url", Target: "findings[].references"},
		{Path: "/template-encoded", Ignored: "the whole template, base64"},
		{Path: "/info", Target: Container},
		{Path: "/info/name", Target: "findings[].title, message"},
		{Path: "/info/severity", Target: "findings[].severity, native.severity"},
		{Path: "/info/description", Target: "findings[].description"},
		{Path: "/info/author", Target: "findings[].source_extra.authors (template authors)"},
		{Path: "/info/author[]", Target: "findings[].source_extra.authors (template authors)"},
		{Path: "/info/tags", Target: "findings[].tags"},
		{Path: "/info/tags[]", Target: "findings[].tags"},
		{Path: "/info/reference", Target: "findings[].references"},
		{Path: "/info/reference[]", Target: "findings[].references"},
		{Path: "/info/remediation", Target: "findings[].remediation.recommendation"},
		{Path: "/info/impact", Target: "findings[].source_extra.impact"},
		{Path: "/info/metadata", Target: "findings[].source_extra.template_metadata"},
		{Path: "/info/metadata/**", Target: "findings[].source_extra.template_metadata"},
		{Path: "/info/classification", Target: Container},
		{Path: "/info/classification/cve-id", Target: "findings[].vulnerability.cve_id, cve_ids, ids"},
		{Path: "/info/classification/cve-id[]", Target: "findings[].vulnerability.cve_id, cve_ids, ids"},
		{Path: "/info/classification/cwe-id", Target: "findings[].vulnerability.cwe_ids"},
		{Path: "/info/classification/cwe-id[]", Target: "findings[].vulnerability.cwe_ids"},
		{Path: "/info/classification/cvss-metrics", Target: "findings[].vulnerability.cvss_vector, scores[].vector"},
		{Path: "/info/classification/cvss-score", Target: "findings[].vulnerability.cvss_score, scores[]"},
		{Path: "/info/classification/epss-score", Target: "findings[].vulnerability.epss_score, scores[] (epss)"},
		{Path: "/info/classification/epss-percentile", Target: "findings[].vulnerability.epss_percentile"},
		{Path: "/info/classification/cpe", Target: "findings[].vulnerability.cpe"},
		{Path: "/type", Target: "findings[].tags (protocol)"},
		{Path: "/host", Target: "assets[] (the host), fingerprint input"},
		{Path: "/port", Target: "findings[].network.port"},
		{Path: "/scheme", Target: "findings[].network.service"},
		{Path: "/url", Ignored: "the target URL; host and matched-at are kept"},
		{Path: "/path", Ignored: "template path on the target; matched-at is kept"},
		{Path: "/matched-at", Target: "findings[].location.path, message (user info removed)"},
		{Path: "/ip", Target: "assets[].properties.ip_address, asset (when no host)"},
		{Path: "/timestamp", Target: "findings[].source_extra.timestamp"},
		{Path: "/matcher-name", Target: "findings[].source_extra.matcher_name"},
		{Path: "/matcher-status", Target: "findings[].confidence (90 when matched, else 70)"},
		{Path: "/extractor-name", Target: "findings[].source_extra.extractor_name"},
		{Path: "/extracted-results", Ignored: "values a template extracted from the target: can hold tokens or personal data"},
		{Path: "/extracted-results[]", Ignored: "values a template extracted from the target: can hold tokens or personal data"},
		{Path: "/curl-command", Ignored: "the request as a command line: can hold cookies and credentials"},
		{Path: "/request", Ignored: "raw HTTP request: can hold cookies and credentials"},
		{Path: "/response", Ignored: "raw HTTP response: can hold data of the target"},
		{Path: "/meta", Ignored: "template variables"},
		{Path: "/meta/**", Ignored: "template variables"},
		{Path: "/matcher-line", Ignored: "line numbers of a file match"},
		{Path: "/matcher-line[]", Ignored: "line numbers of a file match"},
		{Path: "/interaction", Ignored: "out-of-band interaction data: can hold data of the target"},
		{Path: "/interaction/**", Ignored: "out-of-band interaction data: can hold data of the target"},
	},
})
