package importer

const (
	tvR = "/Results[]"
	tvV = tvR + "/Vulnerabilities[]"
	tvM = tvR + "/Misconfigurations[]"
	tvS = tvR + "/Secrets[]"
	tvP = tvR + "/Packages[]"
)

var _ = registerSpec(Spec{
	Format:        FormatTrivy,
	Title:         "trivy JSON",
	SourceVersion: "trivy 0.4x-0.6x --format json (SchemaVersion 2): image, file-system, repository and config scans",
	Rules: []string{
		"Asset: Options.Repository; else the image of an image scan (container asset with image id, OS and digest) or the repository of a repository scan; a file-system scan names a local path, so its findings go to Options.DefaultAsset or an unclassified asset (with an issue).",
		"One finding per vulnerability, misconfiguration and secret. Severity CRITICAL/HIGH/MEDIUM/LOW/UNKNOWN maps to critical/high/medium/low/info; native.severity keeps the word.",
		"Every CVSS source (nvd, ghsa, redhat, ...) and version goes to finding.scores; the legacy vulnerability.cvss_* members take the highest v3 score (nvd first on a tie), else v2.",
		"A secret's match line is masked again with ctis.MaskSecretMatch unless trivy already masked it; the fingerprint input is the masked match.",
		"Packages (--list-all-pkgs) become dependencies with their PURL.",
	},
	Fields: []Field{
		{Path: "/SchemaVersion", Target: "format check"},
		{Path: "/CreatedAt", Ignored: "report time; the import time is the report timestamp"},
		{Path: "/ArtifactName", Target: "assets[].value (image or repository)"},
		{Path: "/ArtifactType", Target: "assets[].type (container, repository)"},
		{Path: "/Metadata", Target: Container},
		{Path: "/Metadata/OS", Target: Container},
		{Path: "/Metadata/OS/Family", Target: "assets[].properties.os"},
		{Path: "/Metadata/OS/Name", Target: "assets[].properties.os"},
		{Path: "/Metadata/ImageID", Target: "assets[].properties.image_id"},
		{Path: "/Metadata/RepoDigests", Target: Container},
		{Path: "/Metadata/RepoDigests[]", Target: "assets[].properties.repo_digest (the first)"},
		{Path: "/Metadata/RepoTags", Ignored: "image tags; the artifact name is kept"},
		{Path: "/Metadata/RepoTags[]", Ignored: "image tags; the artifact name is kept"},
		{Path: "/Metadata/DiffIDs", Ignored: "image layer ids; each vulnerability keeps its layer"},
		{Path: "/Metadata/DiffIDs[]", Ignored: "image layer ids; each vulnerability keeps its layer"},
		{Path: "/Metadata/ImageConfig", Ignored: "image configuration (history, environment, entrypoint): may hold build arguments"},
		{Path: "/Metadata/ImageConfig/**", Ignored: "image configuration (history, environment, entrypoint): may hold build arguments"},
		{Path: "/Metadata/*", Ignored: "other scan metadata"},
		{Path: "/Results", Target: Container},
		{Path: tvR, Target: Container},
		{Path: tvR + "/Target", Target: "findings[].tags, location.path (misconfigurations, secrets), source_extra.target"},
		{Path: tvR + "/Class", Ignored: "result class (os-pkgs, lang-pkgs, config, secret); the record kind says it"},
		{Path: tvR + "/Type", Ignored: "package manager or config kind of the target"},
		{Path: tvR + "/MisconfSummary", Ignored: "counts of passed and failed checks"},
		{Path: tvR + "/MisconfSummary/**", Ignored: "counts of passed and failed checks"},
		{Path: tvR + "/Packages", Target: Container},
		{Path: tvP, Target: "dependencies[]"},
		{Path: tvP + "/ID", Target: "dependencies[].id"},
		{Path: tvP + "/Name", Target: "dependencies[].name"},
		{Path: tvP + "/Version", Target: "dependencies[].version"},
		{Path: tvP + "/Identifier", Target: Container},
		{Path: tvP + "/Identifier/PURL", Target: "dependencies[].purl"},
		{Path: tvP + "/Identifier/UID", Target: "dependencies[].uid"},
		{Path: tvP + "/Licenses", Target: Container},
		{Path: tvP + "/Licenses[]", Target: "dependencies[].licenses"},
		{Path: tvP + "/DependsOn", Target: Container},
		{Path: tvP + "/DependsOn[]", Target: "dependencies[].depends_on"},
		{Path: tvP + "/Relationship", Target: "dependencies[].relationship"},
		{Path: tvP + "/*", Ignored: "other package details (layer, arch, source package, file path)"},
		{Path: tvP + "/*/**", Ignored: "other package details (layer, arch, source package, file path)"},
		{Path: tvR + "/Vulnerabilities", Target: Container},
		{Path: tvV, Target: "findings[] (vulnerability)"},
		{Path: tvV + "/VulnerabilityID", Target: "findings[].rule_id, native.vuln_id, vulnerability.ids, cve_id"},
		{Path: tvV + "/VendorIDs", Target: Container},
		{Path: tvV + "/VendorIDs[]", Target: "findings[].vulnerability.ids[] (vendor)"},
		{Path: tvV + "/PkgID", Target: "findings[].source_extra.pkg_id"},
		{Path: tvV + "/PkgName", Target: "findings[].vulnerability.package"},
		{Path: tvV + "/PkgPath", Target: "findings[].location.path"},
		{Path: tvV + "/PkgIdentifier", Target: Container},
		{Path: tvV + "/PkgIdentifier/PURL", Target: "findings[].vulnerability.purl"},
		{Path: tvV + "/PkgIdentifier/UID", Ignored: "trivy-internal package uid"},
		{Path: tvV + "/InstalledVersion", Target: "findings[].vulnerability.affected_version"},
		{Path: tvV + "/FixedVersion", Target: "findings[].vulnerability.fixed_version, remediation"},
		{Path: tvV + "/Status", Target: "findings[].vulnerability.vuln_status"},
		{Path: tvV + "/SeveritySource", Target: "findings[].vulnerability.severity_source"},
		{Path: tvV + "/Severity", Target: "findings[].severity, native.severity"},
		{Path: tvV + "/VendorSeverity", Target: "findings[].vulnerability.vendor_severity"},
		{Path: tvV + "/VendorSeverity/*", Target: "findings[].vulnerability.vendor_severity"},
		{Path: tvV + "/Title", Target: "findings[].title"},
		{Path: tvV + "/Description", Target: "findings[].description"},
		{Path: tvV + "/PrimaryURL", Target: "findings[].references"},
		{Path: tvV + "/DataSource", Target: Container},
		{Path: tvV + "/DataSource/ID", Target: "findings[].vulnerability.data_source.id"},
		{Path: tvV + "/DataSource/Name", Target: "findings[].vulnerability.data_source.name"},
		{Path: tvV + "/DataSource/URL", Target: "findings[].vulnerability.data_source.url"},
		{Path: tvV + "/CVSS", Target: Container},
		{Path: tvV + "/CVSS/*", Target: Container},
		{Path: tvV + "/CVSS/*/V2Vector", Target: "findings[].scores[] (cvss 2.0)"},
		{Path: tvV + "/CVSS/*/V2Score", Target: "findings[].scores[] (cvss 2.0), vulnerability.cvss_score (when no v3)"},
		{Path: tvV + "/CVSS/*/V3Vector", Target: "findings[].scores[] (cvss 3.x), vulnerability.cvss_vector"},
		{Path: tvV + "/CVSS/*/V3Score", Target: "findings[].scores[] (cvss 3.x), vulnerability.cvss_score"},
		{Path: tvV + "/CVSS/*/V40Vector", Target: "findings[].scores[] (cvss 4.0)"},
		{Path: tvV + "/CVSS/*/V40Score", Target: "findings[].scores[] (cvss 4.0)"},
		{Path: tvV + "/CweIDs", Target: Container},
		{Path: tvV + "/CweIDs[]", Target: "findings[].vulnerability.cwe_ids"},
		{Path: tvV + "/References", Target: Container},
		{Path: tvV + "/References[]", Target: "findings[].references"},
		{Path: tvV + "/PublishedDate", Target: "findings[].vulnerability.published_at"},
		{Path: tvV + "/LastModifiedDate", Target: "findings[].vulnerability.modified_at"},
		{Path: tvV + "/Layer", Target: Container},
		{Path: tvV + "/Layer/Digest", Target: "findings[].vulnerability.layer.digest"},
		{Path: tvV + "/Layer/DiffID", Target: "findings[].vulnerability.layer.diff_id"},
		{Path: tvR + "/Misconfigurations", Target: Container},
		{Path: tvM, Target: "findings[] (misconfiguration)"},
		{Path: tvM + "/Type", Target: "findings[].source_extra.misconfig_type"},
		{Path: tvM + "/ID", Target: "findings[].rule_id, misconfiguration.policy_id"},
		{Path: tvM + "/AVDID", Target: "findings[].misconfiguration.avd_id"},
		{Path: tvM + "/Title", Target: "findings[].title, misconfiguration.policy_name"},
		{Path: tvM + "/Description", Target: "findings[].description"},
		{Path: tvM + "/Message", Target: "findings[].message"},
		{Path: tvM + "/Namespace", Target: "findings[].misconfiguration.namespace"},
		{Path: tvM + "/Query", Target: "findings[].misconfiguration.query"},
		{Path: tvM + "/Resolution", Target: "findings[].remediation.recommendation"},
		{Path: tvM + "/Severity", Target: "findings[].severity, native.severity"},
		{Path: tvM + "/PrimaryURL", Target: "findings[].references"},
		{Path: tvM + "/References", Target: Container},
		{Path: tvM + "/References[]", Target: "findings[].references"},
		{Path: tvM + "/Status", Target: "findings[].native.status"},
		{Path: tvM + "/CauseMetadata", Target: Container},
		{Path: tvM + "/CauseMetadata/Resource", Target: "findings[].misconfiguration.resource_name"},
		{Path: tvM + "/CauseMetadata/Provider", Target: "findings[].misconfiguration.provider"},
		{Path: tvM + "/CauseMetadata/Service", Target: "findings[].misconfiguration.service"},
		{Path: tvM + "/CauseMetadata/StartLine", Target: "findings[].location.start_line"},
		{Path: tvM + "/CauseMetadata/EndLine", Target: "findings[].location.end_line"},
		{Path: tvM + "/CauseMetadata/Code", Ignored: "the source lines of the cause; may hold configuration values"},
		{Path: tvM + "/CauseMetadata/Code/**", Ignored: "the source lines of the cause; may hold configuration values"},
		{Path: tvM + "/CauseMetadata/*", Ignored: "other cause details"},
		{Path: tvM + "/Layer", Ignored: "image layer of the configuration file"},
		{Path: tvM + "/Layer/**", Ignored: "image layer of the configuration file"},
		{Path: tvR + "/Secrets", Target: Container},
		{Path: tvS, Target: "findings[] (secret)"},
		{Path: tvS + "/RuleID", Target: "findings[].rule_id, native.vuln_id"},
		{Path: tvS + "/Category", Target: "findings[].secret.secret_type, source_extra.category"},
		{Path: tvS + "/Severity", Target: "findings[].severity, native.severity"},
		{Path: tvS + "/Title", Target: "findings[].title"},
		{Path: tvS + "/StartLine", Target: "findings[].location.start_line"},
		{Path: tvS + "/EndLine", Target: "findings[].location.end_line"},
		{Path: tvS + "/Match", Target: "findings[].location.snippet (masked), fingerprint input (masked)"},
		{Path: tvS + "/Code", Ignored: "the source lines around the secret; they hold the secret"},
		{Path: tvS + "/Code/**", Ignored: "the source lines around the secret; they hold the secret"},
		{Path: tvS + "/Layer", Ignored: "image layer of the file"},
		{Path: tvS + "/Layer/**", Ignored: "image layer of the file"},
	},
})
