package importer

const (
	sgR  = "/results[]"
	sgEx = sgR + "/extra"
	sgMd = sgEx + "/metadata"
)

var _ = registerSpec(Spec{
	Format:        FormatSemgrep,
	Title:         "semgrep JSON output",
	SourceVersion: "semgrep 1.x --json",
	Rules: []string{
		"One finding per result, filed on Options.Repository, else Options.DefaultAsset, else an unclassified asset named after the tool (with an issue).",
		"Severity: ERROR high, WARNING medium, INFO low, INVENTORY and EXPERIMENT info; native.severity keeps the word. Confidence from metadata.confidence (HIGH 90, MEDIUM 70, LOW 50).",
		"The placeholder \"requires login\" that semgrep writes in fingerprint and lines without a login is no value and is dropped; the fingerprint is then derived from path, rule and line.",
		"A taint trace is read in both forms semgrep writes (objects, or the tagged [\"CliLoc\", [location, content]]); call steps are skipped.",
		"An ignored result (nosemgrep) gets an in-source suppression. Errors become issues.",
	},
	Fields: []Field{
		{Path: "/version", Target: "tool.version"},
		{Path: "/results", Target: Container},
		{Path: sgR, Target: "findings[]"},
		{Path: sgR + "/check_id", Target: "findings[].rule_id, rule_name, native.vuln_id"},
		{Path: sgR + "/path", Target: "findings[].location.path"},
		{Path: sgR + "/start", Target: Container},
		{Path: sgR + "/start/line", Target: "findings[].location.start_line"},
		{Path: sgR + "/start/col", Target: "findings[].location.start_column"},
		{Path: sgR + "/start/offset", Ignored: "byte offset; line and column are kept"},
		{Path: sgR + "/end", Target: Container},
		{Path: sgR + "/end/line", Target: "findings[].location.end_line"},
		{Path: sgR + "/end/col", Target: "findings[].location.end_column"},
		{Path: sgR + "/end/offset", Ignored: "byte offset; line and column are kept"},
		{Path: sgEx, Target: Container},
		{Path: sgEx + "/message", Target: "findings[].title, message"},
		{Path: sgEx + "/severity", Target: "findings[].severity, native.severity"},
		{Path: sgEx + "/lines", Target: "findings[].location.snippet"},
		{Path: sgEx + "/fingerprint", Target: "findings[].fingerprint"},
		{Path: sgEx + "/is_ignored", Target: "findings[].suppression"},
		{Path: sgEx + "/fix", Target: "findings[].remediation.fix_code"},
		{Path: sgEx + "/fix_regex", Target: Container},
		{Path: sgEx + "/fix_regex/regex", Target: "findings[].remediation.fix_regex.regex"},
		{Path: sgEx + "/fix_regex/replacement", Target: "findings[].remediation.fix_regex.replacement"},
		{Path: sgEx + "/fix_regex/count", Target: "findings[].remediation.fix_regex.count"},
		{Path: sgEx + "/validation_state", Target: "findings[].source_extra.validation_state"},
		{Path: sgEx + "/engine_kind", Target: "findings[].source_extra.engine_kind"},
		{Path: sgEx + "/metavars", Ignored: "matched metavariables: fragments of source code, the snippet is kept"},
		{Path: sgEx + "/metavars/**", Ignored: "matched metavariables: fragments of source code, the snippet is kept"},
		{Path: sgEx + "/dataflow_trace", Target: "findings[].data_flow"},
		{Path: sgEx + "/dataflow_trace/taint_source", Target: "findings[].data_flow.sources"},
		{Path: sgEx + "/dataflow_trace/taint_source[]/**", Target: "findings[].data_flow.sources (location path, start line and column, content)"},
		{Path: sgEx + "/dataflow_trace/taint_source[][]/**", Target: "findings[].data_flow.sources (tagged form: location path, start line and column)"},
		{Path: sgEx + "/dataflow_trace/taint_sink[][]/**", Target: "findings[].data_flow.sinks (tagged form: location path, start line and column)"},
		{Path: sgEx + "/dataflow_trace/intermediate_vars", Target: "findings[].data_flow.intermediates"},
		{Path: sgEx + "/dataflow_trace/intermediate_vars[]/**", Target: "findings[].data_flow.intermediates (location path, start line and column, content)"},
		{Path: sgEx + "/dataflow_trace/taint_sink", Target: "findings[].data_flow.sinks"},
		{Path: sgEx + "/dataflow_trace/taint_sink[]/**", Target: "findings[].data_flow.sinks (location path, start line and column, content)"},
		{Path: sgMd, Target: Container},
		{Path: sgMd + "/cwe", Target: "findings[].vulnerability.cwe_ids"},
		{Path: sgMd + "/cwe[]", Target: "findings[].vulnerability.cwe_ids"},
		{Path: sgMd + "/owasp", Target: "findings[].vulnerability.owasp_ids"},
		{Path: sgMd + "/owasp[]", Target: "findings[].vulnerability.owasp_ids"},
		{Path: sgMd + "/confidence", Target: "findings[].confidence"},
		{Path: sgMd + "/impact", Target: "findings[].impact"},
		{Path: sgMd + "/likelihood", Target: "findings[].likelihood"},
		{Path: sgMd + "/category", Target: "findings[].category"},
		{Path: sgMd + "/subcategory", Target: "findings[].subcategory"},
		{Path: sgMd + "/subcategory[]", Target: "findings[].subcategory"},
		{Path: sgMd + "/technology", Target: "findings[].tags"},
		{Path: sgMd + "/technology[]", Target: "findings[].tags"},
		{Path: sgMd + "/references", Target: "findings[].references"},
		{Path: sgMd + "/references[]", Target: "findings[].references"},
		{Path: sgMd + "/vulnerability_class", Target: "findings[].vulnerability_class"},
		{Path: sgMd + "/vulnerability_class[]", Target: "findings[].vulnerability_class"},
		{Path: sgMd + "/source", Target: "findings[].source_extra.rule_source"},
		{Path: sgMd + "/source-rule-url", Target: "findings[].references"},
		{Path: sgMd + "/shortlink", Target: "findings[].references"},
		{Path: sgMd + "/license", Target: "findings[].source_extra.rule_license"},
		{Path: sgMd + "/*", Ignored: "other rule metadata (rule authoring details)"},
		{Path: sgMd + "/*/**", Ignored: "other rule metadata (rule authoring details)"},
		{Path: "/errors", Target: Container},
		{Path: "/errors[]", Target: "issues"},
		{Path: "/errors[]/message", Target: "issues (message)"},
		{Path: "/errors[]/type", Target: "issues (kind)"},
		{Path: "/errors[]/path", Target: "issues (path)"},
		{Path: "/errors[]/type[][]/**", Ignored: "spans of the error kind; the path is kept"},
		{Path: "/errors[]/type[]", Ignored: "spans of the error kind; the path is kept"},
		{Path: "/errors[]/code", Ignored: "exit-code class of the error"},
		{Path: "/errors[]/level", Ignored: "error level; every error becomes an issue"},
		{Path: "/errors[]/spans", Ignored: "source spans of a parse error; the path is kept"},
		{Path: "/errors[]/spans[]/**", Ignored: "source spans of a parse error; the path is kept"},
		{Path: "/paths", Ignored: "the files semgrep scanned (scan operation details)"},
		{Path: "/paths/**", Ignored: "the files semgrep scanned (scan operation details)"},
		{Path: "/time", Ignored: "timing statistics"},
		{Path: "/time/**", Ignored: "timing statistics"},
		{Path: "/profiling_results", Ignored: "timing statistics"},
		{Path: "/profiling_results/**", Ignored: "timing statistics"},
		{Path: "/skipped_rules", Ignored: "rules semgrep did not run"},
		{Path: "/skipped_rules/**", Ignored: "rules semgrep did not run"},
		{Path: "/engine_requested", Ignored: "engine kind of the run"},
		{Path: "/interfile_languages_used", Ignored: "engine detail of the run"},
		{Path: "/interfile_languages_used/**", Ignored: "engine detail of the run"},
	},
})
