package importer

const (
	csDoc  = "/document"
	csTree = "/product_tree"
	csVuln = "/vulnerabilities[]"
	csHelp = csTree + "/**/product_identification_helper"
)

var _ = registerSpec(Spec{
	Format:        FormatCSAF,
	Title:         "CSAF 2.0 (VEX and security advisory profiles)",
	SourceVersion: "CSAF 2.0 JSON (csaf_vex, csaf_security_advisory, csaf_base)",
	Rules: []string{
		"A CSAF document describes products, not findings: the report has no assets or findings, and Result.VEX holds one statement per vulnerability, product_status group and statement text.",
		"Status groups: known_not_affected is not_affected; known_affected, first_affected and last_affected are affected; fixed, first_fixed and recommended are fixed; under_investigation is under_investigation.",
		"not_affected: the justification is the label of a flag that names the product (directly or through a product group); the statement is the details of an impact threat for the product. A not_affected product with neither is left out with an issue: a bare claim never suppresses a finding.",
		"affected and fixed: the statement is the remediation for the product (`category: details (url)`). Nothing is invented when there is none.",
		"Products are resolved through the product tree: branches (any depth; a product_version branch gives the version), full_product_names, and relationships (the platform, with the component in products[].subcomponents). PURL and CPE come from product_identification_helper; a product without them keeps its name.",
		"Product ids the tree does not define, and relationships that refer to undefined or circular products, are left out with an issue.",
		"Statement source: publisher.namespace#tracking.id; as_of: tracking.current_release_date.",
		"Links in the document (sbom_urls, x_generic_uris, references) are never fetched.",
	},
	Fields: []Field{
		{Path: csDoc, Target: Container},
		{Path: csDoc + "/category", Target: "metadata.properties.category"},
		{Path: csDoc + "/csaf_version", Target: "metadata.properties.csaf_version"},
		{Path: csDoc + "/title", Target: "metadata.properties.title"},
		{Path: csDoc + "/lang", Ignored: "document language"},
		{Path: csDoc + "/source_lang", Ignored: "language of a translated document's source"},
		{Path: csDoc + "/publisher", Target: Container},
		{Path: csDoc + "/publisher/name", Target: "metadata.properties.publisher"},
		{Path: csDoc + "/publisher/namespace", Target: "vex[].vex.source, metadata.properties.publisher_namespace"},
		{Path: csDoc + "/publisher/category", Ignored: "kind of publisher (vendor, coordinator, ...)"},
		{Path: csDoc + "/publisher/contact_details", Ignored: "publisher contact (personal data)"},
		{Path: csDoc + "/publisher/issuing_authority", Ignored: "publisher's authority statement (prose)"},
		{Path: csDoc + "/tracking", Target: Container},
		{Path: csDoc + "/tracking/id", Target: "metadata.source_ref, vex[].vex.source"},
		{Path: csDoc + "/tracking/version", Target: "metadata.properties.document_version"},
		{Path: csDoc + "/tracking/status", Target: "metadata.properties.document_status"},
		{Path: csDoc + "/tracking/current_release_date", Target: "vex[].vex.as_of, metadata.properties.current_release_date"},
		{Path: csDoc + "/tracking/initial_release_date", Target: "metadata.properties.initial_release_date"},
		{Path: csDoc + "/tracking/aliases", Ignored: "other ids of the document"},
		{Path: csDoc + "/tracking/aliases[]", Ignored: "other ids of the document"},
		{Path: csDoc + "/tracking/generator*/**", Ignored: "the tool that wrote the document"},
		{Path: csDoc + "/tracking/generator", Ignored: "the tool that wrote the document"},
		{Path: csDoc + "/tracking/revision_history*/**", Ignored: "revision log of the document"},
		{Path: csDoc + "/tracking/revision_history", Ignored: "revision log of the document"},
		{Path: csDoc + "/distribution", Target: Container},
		{Path: csDoc + "/distribution/text", Ignored: "distribution prose; the TLP label is kept"},
		{Path: csDoc + "/distribution/tlp", Target: Container},
		{Path: csDoc + "/distribution/tlp/label", Target: "metadata.properties.tlp"},
		{Path: csDoc + "/distribution/tlp/url", Ignored: "link to the TLP definition"},
		{Path: csDoc + "/aggregate_severity", Target: Container},
		{Path: csDoc + "/aggregate_severity/text", Target: "metadata.properties.aggregate_severity"},
		{Path: csDoc + "/aggregate_severity/namespace", Ignored: "namespace of the severity text"},
		{Path: csDoc + "/notes", Ignored: "advisory prose; statements carry the per-product text"},
		{Path: csDoc + "/notes*/**", Ignored: "advisory prose; statements carry the per-product text"},
		{Path: csDoc + "/references", Ignored: "links about the advisory; never fetched"},
		{Path: csDoc + "/references*/**", Ignored: "links about the advisory; never fetched"},
		{Path: csDoc + "/acknowledgments", Ignored: "names of people and organizations (personal data)"},
		{Path: csDoc + "/acknowledgments*/**", Ignored: "names of people and organizations (personal data)"},

		{Path: csTree, Target: Container},
		{Path: csTree + "/**/branches", Target: Container},
		{Path: csTree + "/**/branches[]", Target: Container},
		{Path: csTree + "/**/branches[]/category", Target: "vex[].products[].version (a product_version branch)"},
		{Path: csTree + "/**/branches[]/name", Target: "vex[].products[].version (a product_version branch; vendor and product names are in the product name)"},
		{Path: csTree + "/**/branches[]/product", Target: Container},
		{Path: csTree + "/**/branches[]/product/name", Target: "vex[].products[].name"},
		{Path: csTree + "/**/branches[]/product/product_id", Target: "(product id the statements refer to)"},
		{Path: csTree + "/full_product_names", Target: Container},
		{Path: csTree + "/full_product_names[]", Target: Container},
		{Path: csTree + "/full_product_names[]/name", Target: "vex[].products[].name"},
		{Path: csTree + "/full_product_names[]/product_id", Target: "(product id the statements refer to)"},
		{Path: csTree + "/relationships", Target: Container},
		{Path: csTree + "/relationships[]", Target: Container},
		{Path: csTree + "/relationships[]/category", Target: "vex[].products[].subcomponents (every category: the component inside the platform)"},
		{Path: csTree + "/relationships[]/product_reference", Target: "vex[].products[].subcomponents[]"},
		{Path: csTree + "/relationships[]/relates_to_product_reference", Target: "vex[].products[] (the platform: its PURL or CPE when the relationship has none)"},
		{Path: csTree + "/relationships[]/full_product_name", Target: Container},
		{Path: csTree + "/relationships[]/full_product_name/name", Target: "vex[].products[].name"},
		{Path: csTree + "/relationships[]/full_product_name/product_id", Target: "(product id the statements refer to)"},
		{Path: csTree + "/product_groups", Target: Container},
		{Path: csTree + "/product_groups[]", Target: Container},
		{Path: csTree + "/product_groups[]/group_id", Target: "(group id flags, threats and remediations refer to)"},
		{Path: csTree + "/product_groups[]/product_ids", Target: Container},
		{Path: csTree + "/product_groups[]/product_ids[]", Target: "(the products of the group)"},
		{Path: csTree + "/product_groups[]/summary", Ignored: "description of the group"},
		{Path: csHelp, Target: Container},
		{Path: csHelp + "/purl", Target: "vex[].products[].purl"},
		{Path: csHelp + "/cpe", Target: "vex[].products[].cpe"},
		{Path: csHelp + "/hashes", Ignored: "file hashes; findings are matched on PURL and CPE"},
		{Path: csHelp + "/hashes*/**", Ignored: "file hashes; findings are matched on PURL and CPE"},
		{Path: csHelp + "/model_numbers", Ignored: "hardware model numbers; no CTIS member"},
		{Path: csHelp + "/model_numbers[]", Ignored: "hardware model numbers; no CTIS member"},
		{Path: csHelp + "/serial_numbers", Ignored: "hardware serial numbers; no CTIS member"},
		{Path: csHelp + "/serial_numbers[]", Ignored: "hardware serial numbers; no CTIS member"},
		{Path: csHelp + "/skus", Ignored: "stock keeping units; no CTIS member"},
		{Path: csHelp + "/skus[]", Ignored: "stock keeping units; no CTIS member"},
		{Path: csHelp + "/sbom_urls", Ignored: "links to SBOMs; never fetched"},
		{Path: csHelp + "/sbom_urls[]", Ignored: "links to SBOMs; never fetched"},
		{Path: csHelp + "/x_generic_uris", Ignored: "other identifiers by URI; never fetched"},
		{Path: csHelp + "/x_generic_uris*/**", Ignored: "other identifiers by URI; never fetched"},

		{Path: "/vulnerabilities", Target: Container},
		{Path: csVuln, Target: "vex[] (one statement per status group and statement text)"},
		{Path: csVuln + "/cve", Target: "vex[].vulnerability_ids (cve)"},
		{Path: csVuln + "/ids", Target: Container},
		{Path: csVuln + "/ids[]", Target: Container},
		{Path: csVuln + "/ids[]/text", Target: "vex[].vulnerability_ids"},
		{Path: csVuln + "/ids[]/system_name", Target: "vex[].vulnerability_ids[].source (vendor ids)"},
		{Path: csVuln + "/product_status", Target: Container},
		{Path: csVuln + "/product_status/*", Target: "vex[].vex.status (by group)"},
		{Path: csVuln + "/product_status/*[]", Target: "vex[].products"},
		{Path: csVuln + "/flags", Target: Container},
		{Path: csVuln + "/flags[]", Target: Container},
		{Path: csVuln + "/flags[]/label", Target: "vex[].vex.justification, native_justification"},
		{Path: csVuln + "/flags[]/product_ids", Target: Container},
		{Path: csVuln + "/flags[]/product_ids[]", Target: "(products the justification is for)"},
		{Path: csVuln + "/flags[]/group_ids", Target: Container},
		{Path: csVuln + "/flags[]/group_ids[]", Target: "(product groups the justification is for)"},
		{Path: csVuln + "/flags[]/date", Ignored: "date of the flag; the document date is the statement date"},
		{Path: csVuln + "/threats", Target: Container},
		{Path: csVuln + "/threats[]", Target: Container},
		{Path: csVuln + "/threats[]/category", Target: "(impact threats give the not_affected statement)"},
		{Path: csVuln + "/threats[]/details", Target: "vex[].vex.statement (not_affected)"},
		{Path: csVuln + "/threats[]/product_ids", Target: Container},
		{Path: csVuln + "/threats[]/product_ids[]", Target: "(products the threat is for)"},
		{Path: csVuln + "/threats[]/group_ids", Target: Container},
		{Path: csVuln + "/threats[]/group_ids[]", Target: "(product groups the threat is for)"},
		{Path: csVuln + "/threats[]/date", Ignored: "date of the threat; the document date is the statement date"},
		{Path: csVuln + "/remediations", Target: Container},
		{Path: csVuln + "/remediations[]", Target: Container},
		{Path: csVuln + "/remediations[]/category", Target: "vex[].vex.statement (affected, fixed)"},
		{Path: csVuln + "/remediations[]/details", Target: "vex[].vex.statement (affected, fixed)"},
		{Path: csVuln + "/remediations[]/url", Target: "vex[].vex.statement (affected, fixed); never fetched"},
		{Path: csVuln + "/remediations[]/product_ids", Target: Container},
		{Path: csVuln + "/remediations[]/product_ids[]", Target: "(products the remediation is for)"},
		{Path: csVuln + "/remediations[]/group_ids", Target: Container},
		{Path: csVuln + "/remediations[]/group_ids[]", Target: "(product groups the remediation is for)"},
		{Path: csVuln + "/remediations[]/date", Ignored: "date of the remediation"},
		{Path: csVuln + "/remediations[]/entitlements", Ignored: "who may get the fix (licensing prose)"},
		{Path: csVuln + "/remediations[]/entitlements[]", Ignored: "who may get the fix (licensing prose)"},
		{Path: csVuln + "/remediations[]/restart_required", Ignored: "operational detail of applying the fix"},
		{Path: csVuln + "/remediations[]/restart_required*/**", Ignored: "operational detail of applying the fix"},
		{Path: csVuln + "/scores", Ignored: "per-product CVSS of the advisory; a statement carries no scores, and the receiver's findings keep their own"},
		{Path: csVuln + "/scores*/**", Ignored: "per-product CVSS of the advisory; a statement carries no scores, and the receiver's findings keep their own"},
		{Path: csVuln + "/cwe", Ignored: "weakness of the vulnerability; a statement carries no weakness"},
		{Path: csVuln + "/cwe*/**", Ignored: "weakness of the vulnerability; a statement carries no weakness"},
		{Path: csVuln + "/title", Ignored: "vulnerability title (advisory prose)"},
		{Path: csVuln + "/notes", Ignored: "vulnerability prose; statements carry the per-product text"},
		{Path: csVuln + "/notes*/**", Ignored: "vulnerability prose; statements carry the per-product text"},
		{Path: csVuln + "/references", Ignored: "links about the vulnerability; never fetched"},
		{Path: csVuln + "/references*/**", Ignored: "links about the vulnerability; never fetched"},
		{Path: csVuln + "/acknowledgments", Ignored: "names of people and organizations (personal data)"},
		{Path: csVuln + "/acknowledgments*/**", Ignored: "names of people and organizations (personal data)"},
		{Path: csVuln + "/involvements", Ignored: "coordination log of the parties"},
		{Path: csVuln + "/involvements*/**", Ignored: "coordination log of the parties"},
		{Path: csVuln + "/discovery_date", Ignored: "when the vulnerability was discovered"},
		{Path: csVuln + "/release_date", Ignored: "when the vulnerability was published"},
	},
})
