package importer

const (
	nsRoot = "/NessusClientData_v2"
	nsHost = nsRoot + "/Report/ReportHost"
	nsTag  = nsHost + "/HostProperties/tag"
	nsItem = nsHost + "/ReportItem"
)

var _ = registerSpec(Spec{
	Format:        FormatNessus,
	Title:         "Nessus v2 XML (.nessus)",
	SourceVersion: "NessusClientData_v2 as written by Nessus 10.x and Tenable.sc 6.x",
	Rules: []string{
		"One asset per ReportHost: value is host-fqdn, else host-ip, else the ReportHost name; type ip_address when the value is an IP address, else host. Asset id `host-<value>`.",
		"One finding per ReportItem: type vulnerability, or compliance when the item carries compliance-check-name.",
		"Severity: the severity attribute (0-4) through ctis.NormalizeNativeSeverity (0 info, 1 low, 2 medium, 3 high, 4 critical); risk_factor when the attribute is unusable. native.severity keeps the attribute; severity 0 sets native.detection_type info.",
		"Every CVSS version goes to finding.scores with source tenable. The legacy vulnerability.cvss_* members take the first of v3, v4, v2, with cvss_source vendor.",
		"plugin_output and compliance-actual-value go to evidence after credential redaction: account lines (User:, Login:, Account:), `as '<account>'`, and password, secret, token, API key and community values become [redacted].",
		"The Policy element (server and plugin preferences, which hold scan credentials and account names) is skipped whole, and smb-login-used, ssh-login-used and compliance-uname are never read.",
		"Values are cleaned of control characters and cut to the CTIS receiver caps (title 500, description 32 KiB, evidence 64 KiB, remediation 16 KiB).",
	},
	Fields: []Field{
		{Path: nsRoot, Target: Container},
		{Path: nsRoot + "/Policy", Ignored: "scan policy: preferences hold credentials and account names"},
		{Path: nsRoot + "/Policy/**", Ignored: "scan policy: preferences hold credentials and account names"},
		{Path: nsRoot + "/Report", Target: Container},
		{Path: nsRoot + "/Report/@name", Target: "metadata.properties.scan_name"},
		{Path: nsHost, Target: "assets[]"},
		{Path: nsHost + "/@name", Target: "assets[].value (when no host-fqdn or host-ip)"},
		{Path: nsHost + "/HostProperties", Target: Container},
		{Path: nsTag + "[*]/@name", Target: Container},
		{Path: nsTag + "[host-ip]", Target: "assets[].value, assets[].properties.ip_address"},
		{Path: nsTag + "[host-fqdn]", Target: "assets[].value, assets[].identity_hints.fqdn, assets[].properties.fqdn"},
		{Path: nsTag + "[host-rdns]", Target: "assets[].properties.host_rdns"},
		{Path: nsTag + "[netbios-name]", Target: "assets[].identity_hints.netbios_name"},
		{Path: nsTag + "[mac-address]", Target: "assets[].identity_hints.mac_addresses, assets[].properties.mac_address"},
		{Path: nsTag + "[operating-system]", Target: "assets[].properties.os (first guess)"},
		{Path: nsTag + "[operating-system-conf]", Target: "assets[].properties.os_confidence"},
		{Path: nsTag + "[operating-system-method]", Target: "assets[].properties.os_method"},
		{Path: nsTag + "[os]", Ignored: "OS family word (linux, windows); operating-system is kept"},
		{Path: nsTag + "[system-type]", Target: "assets[].properties.system_type"},
		{Path: nsTag + "[cpe]", Target: "assets[].identity_hints.os_cpe (an OS CPE)"},
		{Path: nsTag + "[cpe-*]", Target: "assets[].identity_hints.os_cpe (the first OS CPE)"},
		{Path: nsTag + "[bios-uuid]", Target: "assets[].properties.bios_uuid"},
		{Path: nsTag + "[aws-instance-instanceId]", Target: "assets[].identity_hints.cloud_resource_id"},
		{Path: nsTag + "[azure-instance-id]", Target: "assets[].identity_hints.cloud_resource_id"},
		{Path: nsTag + "[gcp-instance-id]", Target: "assets[].identity_hints.cloud_resource_id"},
		{Path: nsTag + "[aws-*]", Ignored: "cloud inventory detail beyond the instance id"},
		{Path: nsTag + "[azure-*]", Ignored: "cloud inventory detail beyond the instance id"},
		{Path: nsTag + "[gcp-*]", Ignored: "cloud inventory detail beyond the instance id"},
		{Path: nsTag + "[nessus-agent-uuid]", Target: "assets[].identity_hints.agent_id"},
		{Path: nsTag + "[tenable-agent-uuid]", Target: "assets[].identity_hints.agent_id"},
		{Path: nsTag + "[agent-uuid]", Target: "assets[].identity_hints.agent_id"},
		{Path: nsTag + "[Credentialed_Scan]", Target: "findings[].native.credentialed"},
		{Path: nsTag + "[HOST_START]", Target: "assets[].properties.scan_started_at (when no timestamp)"},
		{Path: nsTag + "[HOST_START_TIMESTAMP]", Target: "assets[].properties.scan_started_at"},
		{Path: nsTag + "[HOST_END]", Target: "assets[].properties.scan_ended_at (when no timestamp)"},
		{Path: nsTag + "[HOST_END_TIMESTAMP]", Target: "assets[].properties.scan_ended_at"},
		{Path: nsTag + "[local-checks-proto]", Target: "assets[].properties.local_checks_protocol"},
		{Path: nsTag + "[smb-login-used]", Ignored: "the account the scan logged in with"},
		{Path: nsTag + "[ssh-login-used]", Ignored: "the account the scan logged in with"},
		{Path: nsTag + "[ssh-auth-meth]", Ignored: "how the scan authenticated (scan operation detail)"},
		{Path: nsTag + "[ssh-fingerprint]", Ignored: "SSH host key fingerprint seen by the scanner; not an asset identity CTIS defines"},
		{Path: nsTag + "[LastAuthenticatedResults]", Ignored: "scan bookkeeping time"},
		{Path: nsTag + "[LastUnauthenticatedResults]", Ignored: "scan bookkeeping time"},
		{Path: nsTag + "[policy-used]", Ignored: "scan policy name (scan operation detail)"},
		{Path: nsTag + "[patch-summary-*]", Ignored: "summary derived from the plugin results, which are imported"},
		{Path: nsTag + "[traceroute-hop-*]", Ignored: "network path from the scanner, not a property of the host"},
		{Path: nsTag + "[sinfp-*]", Ignored: "raw OS fingerprint signature; operating-system is kept"},
		{Path: nsTag + "[hostname]", Ignored: "duplicate of host-fqdn / netbios-name"},
		{Path: nsTag + "[host_end_timestamp]", Ignored: "duplicate of HOST_END_TIMESTAMP"},
		{Path: nsTag + "[host_start_timestamp]", Ignored: "duplicate of HOST_START_TIMESTAMP"},
		{Path: nsTag + "[id]", Ignored: "scanner-internal host number"},
		{Path: nsTag + "[host-uuid]", Ignored: "scanner-internal host id, unique per scanner database"},
		{Path: nsTag + "[wmi-domain]", Ignored: "Windows domain of the host (directory detail)"},
		{Path: nsTag + "[smb-domain]", Ignored: "Windows domain of the host (directory detail)"},
		{Path: nsTag + "[*]", Ignored: "other host properties (installed software and hardware inventory, scanner bookkeeping); listed by name in Result.Unmapped only when not matched here"},
		{Path: nsItem, Target: "findings[]"},
		{Path: nsItem + "/@port", Target: "findings[].network.port"},
		{Path: nsItem + "/@svc_name", Target: "findings[].network.service"},
		{Path: nsItem + "/@protocol", Target: "findings[].network.protocol"},
		{Path: nsItem + "/@severity", Target: "findings[].severity, findings[].native.severity"},
		{Path: nsItem + "/@pluginID", Target: "findings[].rule_id, findings[].native.vuln_id"},
		{Path: nsItem + "/@pluginName", Target: "findings[].title, findings[].rule_name"},
		{Path: nsItem + "/@pluginFamily", Target: "findings[].category, findings[].native.family"},
		{Path: nsItem + "/plugin_name", Target: "findings[].title (when no pluginName)"},
		{Path: nsItem + "/synopsis", Target: "findings[].message, findings[].description"},
		{Path: nsItem + "/description", Target: "findings[].description"},
		{Path: nsItem + "/solution", Target: "findings[].remediation.recommendation"},
		{Path: nsItem + "/plugin_output", Target: "findings[].evidence (credentials redacted)"},
		{Path: nsItem + "/see_also", Target: "findings[].references"},
		{Path: nsItem + "/risk_factor", Target: "findings[].severity (fallback), findings[].source_extra.risk_factor"},
		{Path: nsItem + "/cve", Target: "findings[].vulnerability.cve_id, cve_ids, ids[] (cve)"},
		{Path: nsItem + "/bid", Target: "findings[].vulnerability.ids[] (vendor, source bid)"},
		{Path: nsItem + "/xref", Target: "findings[].vulnerability.cwe_ids (CWE), ids[] (vendor), remediation.advisories (MSFT, MSKB, IAVA, IAVB, CERT, ...), source_extra.xref"},
		{Path: nsItem + "/msft", Target: "findings[].remediation.advisories (source msft)"},
		{Path: nsItem + "/mskb", Target: "findings[].remediation.advisories (source mskb)"},
		{Path: nsItem + "/iava", Target: "findings[].remediation.advisories (source iava)"},
		{Path: nsItem + "/iavb", Target: "findings[].remediation.advisories (source iavb)"},
		{Path: nsItem + "/iavt", Target: "findings[].remediation.advisories (source iavt)"},
		{Path: nsItem + "/cert", Target: "findings[].remediation.advisories (source cert)"},
		{Path: nsItem + "/cea-id", Target: "findings[].remediation.advisories (source cea-id)"},
		{Path: nsItem + "/cvss_base_score", Target: "findings[].scores[] (cvss 2.0), vulnerability.cvss_score"},
		{Path: nsItem + "/cvss_vector", Target: "findings[].scores[].vector (cvss 2.0), properties.cvss_v2_vector"},
		{Path: nsItem + "/cvss3_base_score", Target: "findings[].scores[] (cvss 3.x), vulnerability.cvss_score"},
		{Path: nsItem + "/cvss3_vector", Target: "findings[].scores[].vector (cvss 3.x), properties.cvss_v3_vector"},
		{Path: nsItem + "/cvss4_base_score", Target: "findings[].scores[] (cvss 4.0)"},
		{Path: nsItem + "/cvss4_vector", Target: "findings[].scores[].vector (cvss 4.0)"},
		{Path: nsItem + "/cvss4_base_vector", Target: "findings[].scores[].vector (cvss 4.0)"},
		{Path: nsItem + "/cvss_temporal_score", Target: "findings[].source_extra.cvss_temporal_score"},
		{Path: nsItem + "/cvss_temporal_vector", Target: "findings[].source_extra.cvss_temporal_vector"},
		{Path: nsItem + "/cvss3_temporal_score", Target: "findings[].source_extra.cvss3_temporal_score"},
		{Path: nsItem + "/cvss3_temporal_vector", Target: "findings[].source_extra.cvss3_temporal_vector"},
		{Path: nsItem + "/cvss3_impact_score", Target: "findings[].source_extra.cvss3_impact_score"},
		{Path: nsItem + "/cvssV3_impact_score", Target: "findings[].source_extra.cvssV3_impact_score"},
		{Path: nsItem + "/cvss4_threat_score", Target: "findings[].source_extra.cvss4_threat_score"},
		{Path: nsItem + "/cvss4_threat_vector", Target: "findings[].source_extra.cvss4_threat_vector"},
		{Path: nsItem + "/cvss_score_source", Target: "findings[].source_extra.cvss_score_source"},
		{Path: nsItem + "/cvss3_score_source", Target: "findings[].source_extra.cvss3_score_source"},
		{Path: nsItem + "/vpr_score", Target: "findings[].scores[] (vpr), vulnerability.vpr_score"},
		{Path: nsItem + "/epss_score", Target: "findings[].scores[] (epss), vulnerability.epss_score"},
		{Path: nsItem + "/exploit_available", Target: "findings[].vulnerability.exploit_available"},
		{Path: nsItem + "/exploit_code_maturity", Target: "findings[].vulnerability.exploit_maturity, source_extra.exploit_code_maturity"},
		{Path: nsItem + "/exploitability_ease", Target: "findings[].source_extra.exploitability_ease"},
		{Path: nsItem + "/exploit_framework_metasploit", Target: "findings[].source_extra.exploit_framework_metasploit"},
		{Path: nsItem + "/exploit_framework_canvas", Target: "findings[].source_extra.exploit_framework_canvas"},
		{Path: nsItem + "/exploit_framework_core", Target: "findings[].source_extra.exploit_framework_core"},
		{Path: nsItem + "/exploit_framework_d2_elliot", Target: "findings[].source_extra.exploit_framework_d2_elliot"},
		{Path: nsItem + "/exploit_framework_exploithub", Target: "findings[].source_extra.exploit_framework_exploithub"},
		{Path: nsItem + "/metasploit_name", Target: "findings[].source_extra.metasploit_name"},
		{Path: nsItem + "/canvas_package", Target: "findings[].source_extra.canvas_package"},
		{Path: nsItem + "/d2_elliot_name", Target: "findings[].source_extra.d2_elliot_name"},
		{Path: nsItem + "/exploited_by_malware", Target: "findings[].source_extra.exploited_by_malware"},
		{Path: nsItem + "/exploited_by_nessus", Target: "findings[].source_extra.exploited_by_nessus"},
		{Path: nsItem + "/in_the_news", Target: "findings[].source_extra.in_the_news"},
		{Path: nsItem + "/unsupported_by_vendor", Target: "findings[].remediation.solution_type (upgrade), source_extra.unsupported_by_vendor"},
		{Path: nsItem + "/default_account", Target: "findings[].source_extra.default_account"},
		{Path: nsItem + "/cisa-known-exploited", Target: "findings[].vulnerability.in_cisa_kev, source_extra (the KEV due date)"},
		{Path: nsItem + "/cisa_known_exploited", Target: "findings[].vulnerability.in_cisa_kev, source_extra"},
		{Path: nsItem + "/cpe", Target: "findings[].vulnerability.cpe"},
		{Path: nsItem + "/vuln_publication_date", Target: "findings[].vulnerability.published_at, source_extra"},
		{Path: nsItem + "/patch_publication_date", Target: "findings[].remediation.patch_published_at, fix_available, properties.patch_publication_date"},
		{Path: nsItem + "/plugin_publication_date", Target: "findings[].source_extra.plugin_publication_date"},
		{Path: nsItem + "/plugin_modification_date", Target: "findings[].source_extra.plugin_modification_date"},
		{Path: nsItem + "/plugin_type", Target: "findings[].source_extra.plugin_type"},
		{Path: nsItem + "/stig_severity", Target: "findings[].source_extra.stig_severity"},
		{Path: nsItem + "/age_of_vuln", Target: "findings[].source_extra.age_of_vuln"},
		{Path: nsItem + "/threat_intensity_last_28", Target: "findings[].source_extra.threat_intensity_last_28"},
		{Path: nsItem + "/threat_recency", Target: "findings[].source_extra.threat_recency"},
		{Path: nsItem + "/threat_sources_last_28", Target: "findings[].source_extra.threat_sources_last_28"},
		{Path: nsItem + "/product_coverage", Target: "findings[].source_extra.product_coverage"},
		{Path: nsItem + "/vendor_severity", Target: "findings[].source_extra.vendor_severity"},
		{Path: nsItem + "/vendor_unpatched", Target: "findings[].source_extra.vendor_unpatched"},
		{Path: nsItem + "/rhsa", Target: "findings[].source_extra.rhsa"},
		{Path: nsItem + "/usn", Target: "findings[].source_extra.usn"},
		{Path: nsItem + "/dsa", Target: "findings[].source_extra.dsa"},
		{Path: nsItem + "/glsa", Target: "findings[].source_extra.glsa"},
		{Path: nsItem + "/fedora", Target: "findings[].source_extra.fedora"},
		{Path: nsItem + "/suse", Target: "findings[].source_extra.suse"},
		{Path: nsItem + "/osvdb", Target: "findings[].source_extra.osvdb"},
		{Path: nsItem + "/edb-id", Target: "findings[].source_extra.edb-id"},
		{Path: nsItem + "/compliance-check-name", Target: "findings[].type compliance, title, compliance.control_name"},
		{Path: nsItem + "/compliance-check-id", Target: "findings[].compliance.control_id (when no control id), source_extra"},
		{Path: nsItem + "/compliance-control-id", Target: "findings[].compliance.control_id"},
		{Path: nsItem + "/compliance-result", Target: "findings[].compliance.result, source_extra.compliance-result"},
		{Path: nsItem + "/compliance-info", Target: "findings[].compliance.control_description"},
		{Path: nsItem + "/compliance-actual-value", Target: "findings[].evidence (credentials redacted)"},
		{Path: nsItem + "/compliance-policy-value", Target: "findings[].source_extra.compliance-policy-value"},
		{Path: nsItem + "/compliance-solution", Target: "findings[].remediation.recommendation"},
		{Path: nsItem + "/compliance-see-also", Target: "findings[].references"},
		{Path: nsItem + "/compliance-reference", Target: "findings[].source_extra.compliance-reference"},
		{Path: nsItem + "/compliance-audit-file", Target: "findings[].source_extra.compliance-audit-file"},
		{Path: nsItem + "/compliance-benchmark-name", Target: "findings[].compliance.framework (cis, nist, pci-dss, ... from the name), source_extra.compliance-benchmark-name"},
		{Path: nsItem + "/compliance-benchmark-version", Target: "findings[].compliance.framework_version"},
		{Path: nsItem + "/compliance-benchmark-profile", Target: "findings[].source_extra.compliance-benchmark-profile"},
		{Path: nsItem + "/compliance-full-id", Target: "findings[].source_extra.compliance-full-id"},
		{Path: nsItem + "/compliance-functional-id", Target: "findings[].source_extra.compliance-functional-id"},
		{Path: nsItem + "/compliance-source", Target: "findings[].source_extra.compliance-source"},
		{Path: nsItem + "/compliance-uname", Ignored: "the account the compliance check ran as"},
		{Path: nsItem + "/compliance", Ignored: "flag duplicating compliance-check-name"},
		{Path: nsItem + "/fname", Ignored: "plugin script file name (scanner internals)"},
		{Path: nsItem + "/script_version", Ignored: "plugin script revision (scanner internals)"},
		{Path: nsItem + "/agent", Ignored: "which scanner kinds run the plugin (scanner internals)"},
		{Path: nsItem + "/thorough_tests", Ignored: "scan setting the plugin needs (scanner internals)"},
		{Path: nsItem + "/always_run", Ignored: "scan setting (scanner internals)"},
		{Path: nsItem + "/required_key", Ignored: "plugin dependency (scanner internals)"},
		{Path: nsItem + "/required_port", Ignored: "plugin dependency (scanner internals)"},
		{Path: nsItem + "/dependency", Ignored: "plugin dependency (scanner internals)"},
		{Path: nsItem + "/asset_inventory", Ignored: "flag for inventory plugins (scanner internals)"},
		{Path: nsItem + "/hardware_inventory", Ignored: "flag for inventory plugins (scanner internals)"},
		{Path: nsItem + "/os_identification", Ignored: "flag for OS identification plugins (scanner internals)"},
		{Path: nsItem + "/asset_inventory_category", Ignored: "inventory plugin category (scanner internals)"},
		{Path: nsItem + "/attachment", Ignored: "binary attachment of the plugin result (screenshots, files); not imported"},
		{Path: nsItem + "/attachment/@*", Ignored: "binary attachment of the plugin result; not imported"},
	},
})
