package importer

const (
	kbRoot = "/KNOWLEDGE_BASE_VULN_LIST_OUTPUT"
	kbResp = kbRoot + "/RESPONSE"
	kbVuln = kbResp + "/VULN_LIST/VULN"
)

var _ = registerSpec(Spec{
	Format:        FormatQualysKB,
	Title:         "Qualys KnowledgeBase XML",
	SourceVersion: "KNOWLEDGE_BASE_VULN_LIST_OUTPUT of the KnowledgeBase API v2 (/api/2.0/fo/knowledge_base/vuln/, details=All)",
	Rules: []string{
		"Read only as the companion of a detection file. Each VULN enriches every finding of its QID; entries of other QIDs are skipped without being kept.",
		"DIAGNOSIS, CONSEQUENCE and SOLUTION are light HTML: line-break and paragraph tags become newlines and every other tag is dropped, so the text is plain text.",
		"CVSS v3 and v2 go to finding.scores with their source attribute (service, nvd, ...); the legacy vulnerability.cvss_* members take v3, else v2.",
		"THREAT_INTELLIGENCE labels become tags; exploit-related ones (Exploit_Public, Easy_Exploit, Active_Attacks, Malware, Exploit_Kit, Wormable, Ransomware, Cisa_Known_Exploited_Vulns) set exploit_available, and Cisa_Known_Exploited_Vulns sets in_cisa_kev.",
	},
	Fields: []Field{
		{Path: kbRoot, Target: Container},
		{Path: kbResp, Target: Container},
		{Path: kbResp + "/DATETIME", Ignored: "generation time of the KnowledgeBase export; the detection file's time is kept"},
		{Path: kbResp + "/VULN_LIST", Target: Container},
		{Path: kbVuln, Target: "findings[] of the QID (enrichment)"},
		{Path: kbVuln + "/QID", Target: "join key"},
		{Path: kbVuln + "/VULN_TYPE", Target: "findings[].native.detection_type (when the detection has no TYPE), source_extra.vuln_type"},
		{Path: kbVuln + "/SEVERITY_LEVEL", Ignored: "the detection's SEVERITY is the severity of the finding"},
		{Path: kbVuln + "/TITLE", Target: "findings[].title, rule_name"},
		{Path: kbVuln + "/CATEGORY", Target: "findings[].category, native.family"},
		{Path: kbVuln + "/TECHNOLOGY", Target: "findings[].source_extra.technology"},
		{Path: kbVuln + "/DETECTION_INFO", Target: "findings[].source_extra.detection_info"},
		{Path: kbVuln + "/LAST_CUSTOMIZATION", Ignored: "KnowledgeBase edit bookkeeping"},
		{Path: kbVuln + "/LAST_CUSTOMIZATION/**", Ignored: "KnowledgeBase edit bookkeeping (who and when)"},
		{Path: kbVuln + "/LAST_SERVICE_MODIFICATION_DATETIME", Target: "findings[].vulnerability.modified_at"},
		{Path: kbVuln + "/PUBLISHED_DATETIME", Target: "findings[].vulnerability.published_at"},
		{Path: kbVuln + "/CODE_MODIFIED_DATETIME", Target: "findings[].source_extra.code_modified_datetime"},
		{Path: kbVuln + "/BUGTRAQ_LIST", Target: Container},
		{Path: kbVuln + "/BUGTRAQ_LIST/BUGTRAQ", Target: Container},
		{Path: kbVuln + "/BUGTRAQ_LIST/BUGTRAQ/ID", Target: "findings[].vulnerability.ids[] (vendor, source bid)"},
		{Path: kbVuln + "/BUGTRAQ_LIST/BUGTRAQ/URL", Target: "findings[].references"},
		{Path: kbVuln + "/PATCHABLE", Target: "findings[].remediation.fix_available, solution_type patch, source_extra.patchable"},
		{Path: kbVuln + "/PATCH_PUBLISHED_DATE", Target: "findings[].remediation.patch_published_at"},
		{Path: kbVuln + "/SOFTWARE_LIST", Target: Container},
		{Path: kbVuln + "/SOFTWARE_LIST/SOFTWARE", Target: Container},
		{Path: kbVuln + "/SOFTWARE_LIST/SOFTWARE/PRODUCT", Target: "findings[].source_extra.affected_software"},
		{Path: kbVuln + "/SOFTWARE_LIST/SOFTWARE/VENDOR", Target: "findings[].source_extra.affected_software"},
		{Path: kbVuln + "/VENDOR_REFERENCE_LIST", Target: Container},
		{Path: kbVuln + "/VENDOR_REFERENCE_LIST/VENDOR_REFERENCE", Target: Container},
		{Path: kbVuln + "/VENDOR_REFERENCE_LIST/VENDOR_REFERENCE/ID", Target: "findings[].remediation.advisories[].id"},
		{Path: kbVuln + "/VENDOR_REFERENCE_LIST/VENDOR_REFERENCE/URL", Target: "findings[].remediation.advisories[].url"},
		{Path: kbVuln + "/CVE_LIST", Target: Container},
		{Path: kbVuln + "/CVE_LIST/CVE", Target: Container},
		{Path: kbVuln + "/CVE_LIST/CVE/ID", Target: "findings[].vulnerability.cve_id, cve_ids, ids[]"},
		{Path: kbVuln + "/CVE_LIST/CVE/URL", Target: "findings[].references"},
		{Path: kbVuln + "/DIAGNOSIS", Target: "findings[].description"},
		{Path: kbVuln + "/DIAGNOSIS_COMMENT", Target: "findings[].source_extra.diagnosis_comment"},
		{Path: kbVuln + "/CONSEQUENCE", Target: "findings[].source_extra.consequence"},
		{Path: kbVuln + "/CONSEQUENCE_COMMENT", Target: "findings[].source_extra.consequence_comment"},
		{Path: kbVuln + "/SOLUTION", Target: "findings[].remediation.recommendation"},
		{Path: kbVuln + "/SOLUTION_COMMENT", Target: "findings[].source_extra.solution_comment"},
		{Path: kbVuln + "/COMPLIANCE_LIST", Target: Container},
		{Path: kbVuln + "/COMPLIANCE_LIST/COMPLIANCE", Target: Container},
		{Path: kbVuln + "/COMPLIANCE_LIST/COMPLIANCE/TYPE", Target: "findings[].source_extra.compliance"},
		{Path: kbVuln + "/COMPLIANCE_LIST/COMPLIANCE/SECTION", Target: "findings[].source_extra.compliance"},
		{Path: kbVuln + "/COMPLIANCE_LIST/COMPLIANCE/DESCRIPTION", Target: "findings[].source_extra.compliance"},
		{Path: kbVuln + "/CORRELATION", Target: Container},
		{Path: kbVuln + "/CORRELATION/EXPLOITS", Target: Container},
		{Path: kbVuln + "/CORRELATION/EXPLOITS/EXPLT_SRC", Target: Container},
		{Path: kbVuln + "/CORRELATION/EXPLOITS/EXPLT_SRC/SRC_NAME", Target: "findings[].source_extra.exploits"},
		{Path: kbVuln + "/CORRELATION/EXPLOITS/EXPLT_SRC/EXPLT_LIST", Target: Container},
		{Path: kbVuln + "/CORRELATION/EXPLOITS/EXPLT_SRC/EXPLT_LIST/EXPLT", Target: "findings[].vulnerability.exploit_available"},
		{Path: kbVuln + "/CORRELATION/EXPLOITS/EXPLT_SRC/EXPLT_LIST/EXPLT/REF", Target: "findings[].source_extra.exploits"},
		{Path: kbVuln + "/CORRELATION/EXPLOITS/EXPLT_SRC/EXPLT_LIST/EXPLT/DESC", Target: "findings[].source_extra.exploits (when no REF)"},
		{Path: kbVuln + "/CORRELATION/EXPLOITS/EXPLT_SRC/EXPLT_LIST/EXPLT/LINK", Target: "findings[].references"},
		{Path: kbVuln + "/CORRELATION/MALWARE", Target: Container},
		{Path: kbVuln + "/CORRELATION/MALWARE/MW_SRC", Target: Container},
		{Path: kbVuln + "/CORRELATION/MALWARE/MW_SRC/SRC_NAME", Target: "findings[].source_extra.malware"},
		{Path: kbVuln + "/CORRELATION/MALWARE/MW_SRC/MW_LIST", Target: Container},
		{Path: kbVuln + "/CORRELATION/MALWARE/MW_SRC/MW_LIST/MW_INFO", Target: Container},
		{Path: kbVuln + "/CORRELATION/MALWARE/MW_SRC/MW_LIST/MW_INFO/MW_ID", Target: "findings[].source_extra.malware"},
		{Path: kbVuln + "/CORRELATION/MALWARE/MW_SRC/MW_LIST/MW_INFO/MW_TYPE", Target: "findings[].source_extra.malware"},
		{Path: kbVuln + "/CORRELATION/MALWARE/MW_SRC/MW_LIST/MW_INFO/MW_RATING", Target: "findings[].source_extra.malware"},
		{Path: kbVuln + "/CORRELATION/MALWARE/MW_SRC/MW_LIST/MW_INFO/MW_PLATFORM", Ignored: "malware platform list; the id, type and rating are kept"},
		{Path: kbVuln + "/CORRELATION/MALWARE/MW_SRC/MW_LIST/MW_INFO/MW_ALIAS", Ignored: "malware aliases; the id is kept"},
		{Path: kbVuln + "/CORRELATION/MALWARE/MW_SRC/MW_LIST/MW_INFO/MW_LINK", Ignored: "link to a malware encyclopedia page"},
		{Path: kbVuln + "/CVSS", Target: Container},
		{Path: kbVuln + "/CVSS/BASE", Target: "findings[].scores[] (cvss 2.0), vulnerability.cvss_score (when no v3)"},
		{Path: kbVuln + "/CVSS/BASE/@source", Target: "findings[].scores[].source"},
		{Path: kbVuln + "/CVSS/TEMPORAL", Target: "findings[].source_extra.cvss2_temporal"},
		{Path: kbVuln + "/CVSS/VECTOR_STRING", Target: "findings[].scores[].vector (cvss 2.0)"},
		{Path: kbVuln + "/CVSS/ACCESS", Ignored: "vector component, kept in the vector string"},
		{Path: kbVuln + "/CVSS/ACCESS/**", Ignored: "vector component, kept in the vector string"},
		{Path: kbVuln + "/CVSS/IMPACT", Ignored: "vector component, kept in the vector string"},
		{Path: kbVuln + "/CVSS/IMPACT/**", Ignored: "vector component, kept in the vector string"},
		{Path: kbVuln + "/CVSS/AUTHENTICATION", Ignored: "vector component, kept in the vector string"},
		{Path: kbVuln + "/CVSS/EXPLOITABILITY", Ignored: "temporal component, kept in the temporal score"},
		{Path: kbVuln + "/CVSS/REMEDIATION_LEVEL", Ignored: "temporal component, kept in the temporal score"},
		{Path: kbVuln + "/CVSS/REPORT_CONFIDENCE", Ignored: "temporal component, kept in the temporal score"},
		{Path: kbVuln + "/CVSS_V3", Target: Container},
		{Path: kbVuln + "/CVSS_V3/BASE", Target: "findings[].scores[] (cvss 3.x), vulnerability.cvss_score"},
		{Path: kbVuln + "/CVSS_V3/BASE/@source", Target: "findings[].scores[].source"},
		{Path: kbVuln + "/CVSS_V3/TEMPORAL", Target: "findings[].source_extra.cvss3_temporal"},
		{Path: kbVuln + "/CVSS_V3/VECTOR_STRING", Target: "findings[].scores[].vector (cvss 3.x), the version"},
		{Path: kbVuln + "/CVSS_V3/CVSS3_VERSION", Target: "findings[].scores[].version (when the vector has none)"},
		{Path: kbVuln + "/CVSS_V3/ATTACK_VECTOR", Ignored: "vector component, kept in the vector string"},
		{Path: kbVuln + "/CVSS_V3/ATTACK_COMPLEXITY", Ignored: "vector component, kept in the vector string"},
		{Path: kbVuln + "/CVSS_V3/PRIVILEGES_REQUIRED", Ignored: "vector component, kept in the vector string"},
		{Path: kbVuln + "/CVSS_V3/USER_INTERACTION", Ignored: "vector component, kept in the vector string"},
		{Path: kbVuln + "/CVSS_V3/SCOPE", Ignored: "vector component, kept in the vector string"},
		{Path: kbVuln + "/CVSS_V3/IMPACT", Ignored: "vector component, kept in the vector string"},
		{Path: kbVuln + "/CVSS_V3/IMPACT/**", Ignored: "vector component, kept in the vector string"},
		{Path: kbVuln + "/CVSS_V3/EXPLOIT_CODE_MATURITY", Ignored: "temporal component, kept in the temporal score"},
		{Path: kbVuln + "/CVSS_V3/REMEDIATION_LEVEL", Ignored: "temporal component, kept in the temporal score"},
		{Path: kbVuln + "/CVSS_V3/REPORT_CONFIDENCE", Ignored: "temporal component, kept in the temporal score"},
		{Path: kbVuln + "/PCI_FLAG", Target: "findings[].tags (pci), source_extra.pci_flag"},
		{Path: kbVuln + "/PCI_REASONS", Target: Container},
		{Path: kbVuln + "/PCI_REASONS/PCI_REASON", Target: "findings[].source_extra.pci_reasons"},
		{Path: kbVuln + "/THREAT_INTELLIGENCE", Target: Container},
		{Path: kbVuln + "/THREAT_INTELLIGENCE/THREAT_INTEL[*]", Target: "findings[].tags, vulnerability.exploit_available, in_cisa_kev"},
		{Path: kbVuln + "/THREAT_INTELLIGENCE/THREAT_INTEL[*]/@id", Target: Container},
		{Path: kbVuln + "/DISCOVERY", Target: Container},
		{Path: kbVuln + "/DISCOVERY/REMOTE", Target: "findings[].source_extra.discovery_remote"},
		{Path: kbVuln + "/DISCOVERY/AUTH_TYPE_LIST", Target: Container},
		{Path: kbVuln + "/DISCOVERY/AUTH_TYPE_LIST/AUTH_TYPE", Target: "findings[].source_extra.discovery_auth_types"},
		{Path: kbVuln + "/DISCOVERY/ADDITIONAL_INFO", Target: "findings[].source_extra.discovery_additional_info"},
		{Path: kbVuln + "/SUPPORTED_MODULES", Ignored: "Qualys product modules that detect the QID"},
		{Path: kbVuln + "/IS_DISABLED", Ignored: "KnowledgeBase entry state; the detection's IS_DISABLED is kept"},
		{Path: kbVuln + "/CHANGE_LOG_LIST", Ignored: "KnowledgeBase revision history"},
		{Path: kbVuln + "/CHANGE_LOG_LIST/**", Ignored: "KnowledgeBase revision history"},
		{Path: kbVuln + "/AUTOMATIC_PCI_FAIL", Ignored: "PCI scan setting"},
	},
})
