package importer

const (
	qRoot  = "/HOST_LIST_VM_DETECTION_OUTPUT"
	qResp  = qRoot + "/RESPONSE"
	qHostP = qResp + "/HOST_LIST/HOST"
	qDet   = qHostP + "/DETECTION_LIST/DETECTION"
)

var _ = registerSpec(Spec{
	Format:        FormatQualys,
	Title:         "Qualys VM host list detection XML",
	SourceVersion: "HOST_LIST_VM_DETECTION_OUTPUT of the VM detection API v2 (/api/2.0/fo/asset/host/vm/detection/), joined with the KnowledgeBase (qualys_kb)",
	Rules: []string{
		"One asset per HOST: value is DNS_DATA/FQDN, else DNS, else IP, else IPV6, else NETBIOS; type ip_address when the value is an IP address, else host. Asset id `host-<value>`.",
		"One finding per DETECTION, keyed by QID: rule_id and native.vuln_id are the QID, native.instance_id the UNIQUE_VULN_ID. Title, description, CVEs, CVSS and the solution come from the KnowledgeBase entry of the QID (qualys_kb.md); without one the title is `Qualys QID <n>` and an issue says so.",
		"Severity: SEVERITY 1-5 through ctis.NormalizeNativeSeverity (1 info, 2 low, 3 medium, 4 high, 5 critical); native.severity keeps it.",
		"TYPE Confirmed / Potential / Info goes to native.detection_type; a Potential detection gets confidence 50.",
		"STATUS New / Active / Re-Opened / Fixed goes to native.status, the normalized finding status and source_lifecycle.state. FIRST_FOUND, LAST_FOUND, LAST_FIXED and TIMES_FOUND go to source_lifecycle (and first_seen_at / last_seen_at).",
		"RESULTS go to evidence after credential redaction (account lines, passwords, tokens, community strings become [redacted]).",
		"Host owner, comments and user-defined fields are never read; asset criticality and risk scores are kept as properties and do not set the CTIS criticality.",
	},
	Fields: []Field{
		{Path: qRoot, Target: Container},
		{Path: qResp, Target: Container},
		{Path: qResp + "/DATETIME", Target: "metadata.properties.generated_at"},
		{Path: qResp + "/WARNING", Ignored: "pagination notice; an issue says the export is one page"},
		{Path: qResp + "/WARNING/**", Ignored: "pagination notice (code, text, next-page URL)"},
		{Path: qResp + "/HOST_LIST", Target: Container},
		{Path: qHostP, Target: "assets[]"},
		{Path: qHostP + "/ID", Target: "assets[].properties.qualys_host_id"},
		{Path: qHostP + "/ASSET_ID", Target: "assets[].properties.qualys_asset_id"},
		{Path: qHostP + "/IP", Target: "assets[].value (when no DNS name), properties.ip_address"},
		{Path: qHostP + "/IPV6", Target: "assets[].value (when no DNS name or IPv4), properties.ipv6_address"},
		{Path: qHostP + "/TRACKING_METHOD", Target: "assets[].properties.tracking_method"},
		{Path: qHostP + "/NETWORK_ID", Target: "assets[].properties.network_id"},
		{Path: qHostP + "/OS", Target: "assets[].properties.os"},
		{Path: qHostP + "/OS_CPE", Target: "assets[].identity_hints.os_cpe"},
		{Path: qHostP + "/DNS", Target: "assets[].value, identity_hints.fqdn (when no DNS_DATA/FQDN)"},
		{Path: qHostP + "/DNS_DATA", Target: Container},
		{Path: qHostP + "/DNS_DATA/HOSTNAME", Target: "assets[].properties.dns_hostname"},
		{Path: qHostP + "/DNS_DATA/DOMAIN", Target: "assets[].properties.dns_domain"},
		{Path: qHostP + "/DNS_DATA/FQDN", Target: "assets[].value, identity_hints.fqdn, properties.fqdn"},
		{Path: qHostP + "/NETBIOS", Target: "assets[].identity_hints.netbios_name"},
		{Path: qHostP + "/CLOUD_PROVIDER", Target: "assets[].properties.cloud_provider"},
		{Path: qHostP + "/CLOUD_SERVICE", Target: "assets[].properties.cloud_service"},
		{Path: qHostP + "/CLOUD_RESOURCE_ID", Target: "assets[].identity_hints.cloud_resource_id"},
		{Path: qHostP + "/EC2_INSTANCE_ID", Target: "assets[].identity_hints.cloud_resource_id (when no CLOUD_RESOURCE_ID)"},
		{Path: qHostP + "/QG_HOSTID", Target: "assets[].identity_hints.agent_id"},
		{Path: qHostP + "/LAST_SCAN_DATETIME", Target: "assets[].properties.last_scan_at"},
		{Path: qHostP + "/LAST_VM_SCANNED_DATE", Target: "assets[].properties.last_vm_scanned_at"},
		{Path: qHostP + "/LAST_VM_SCANNED_DURATION", Target: "assets[].properties.last_vm_scan_duration_s"},
		{Path: qHostP + "/LAST_VM_AUTH_SCANNED_DATE", Target: "assets[].properties.last_vm_auth_scanned_at"},
		{Path: qHostP + "/LAST_VM_AUTH_SCANNED_DURATION", Ignored: "scan bookkeeping"},
		{Path: qHostP + "/LAST_PC_SCANNED_DATE", Target: "assets[].properties.last_pc_scanned_at"},
		{Path: qHostP + "/ASSET_RISK_SCORE", Target: "assets[].properties.qualys_asset_risk_score"},
		{Path: qHostP + "/TRURISK_SCORE", Target: "assets[].properties.qualys_trurisk_score"},
		{Path: qHostP + "/ASSET_CRITICALITY_SCORE", Target: "assets[].properties.qualys_asset_criticality_score"},
		{Path: qHostP + "/TAGS", Target: Container},
		{Path: qHostP + "/TAGS/TAG", Target: Container},
		{Path: qHostP + "/TAGS/TAG/NAME", Target: "assets[].tags"},
		{Path: qHostP + "/TAGS/TAG/TAG_ID", Ignored: "Qualys-internal tag number; the name is kept"},
		{Path: qHostP + "/TAGS/TAG/**", Ignored: "tag colors and rules (presentation)"},
		{Path: qHostP + "/METADATA", Ignored: "cloud instance metadata attributes; the cloud resource id is kept"},
		{Path: qHostP + "/METADATA/**", Ignored: "cloud instance metadata attributes; the cloud resource id is kept"},
		{Path: qHostP + "/CLOUD_PROVIDER_TAGS", Ignored: "cloud provider tags (key/value pairs chosen by the cloud account; may hold names of people)"},
		{Path: qHostP + "/CLOUD_PROVIDER_TAGS/**", Ignored: "cloud provider tags"},
		{Path: qHostP + "/OWNER", Ignored: "the person who owns the host in Qualys (personal data)"},
		{Path: qHostP + "/COMMENTS", Ignored: "free-text comments typed by users"},
		{Path: qHostP + "/USER_DEF", Ignored: "user-defined fields"},
		{Path: qHostP + "/USER_DEF/**", Ignored: "user-defined fields"},
		{Path: qHostP + "/ASSET_GROUP_IDS", Ignored: "Qualys-internal asset group numbers"},
		{Path: qHostP + "/LAST_COMPLIANCE_SCAN_DATETIME", Ignored: "policy compliance bookkeeping"},
		{Path: qHostP + "/DETECTION_LIST", Target: Container},
		{Path: qDet, Target: "findings[]"},
		{Path: qDet + "/UNIQUE_VULN_ID", Target: "findings[].native.instance_id"},
		{Path: qDet + "/QID", Target: "findings[].rule_id, native.vuln_id (the KnowledgeBase join key)"},
		{Path: qDet + "/TYPE", Target: "findings[].native.detection_type, confidence, source_extra.type"},
		{Path: qDet + "/SEVERITY", Target: "findings[].severity, native.severity"},
		{Path: qDet + "/PORT", Target: "findings[].network.port"},
		{Path: qDet + "/PROTOCOL", Target: "findings[].network.protocol"},
		{Path: qDet + "/FQDN", Target: "findings[].network.host"},
		{Path: qDet + "/SSL", Target: "findings[].source_extra.ssl"},
		{Path: qDet + "/INSTANCE", Target: "findings[].source_extra.instance"},
		{Path: qDet + "/RESULTS", Target: "findings[].evidence (credentials redacted)"},
		{Path: qDet + "/STATUS", Target: "findings[].status, native.status, source_lifecycle.state"},
		{Path: qDet + "/FIRST_FOUND_DATETIME", Target: "findings[].source_lifecycle.first_found, first_seen_at"},
		{Path: qDet + "/LAST_FOUND_DATETIME", Target: "findings[].source_lifecycle.last_found, last_seen_at"},
		{Path: qDet + "/TIMES_FOUND", Target: "findings[].source_lifecycle.times_found"},
		{Path: qDet + "/LAST_FIXED_DATETIME", Target: "findings[].source_lifecycle.last_fixed"},
		{Path: qDet + "/LAST_TEST_DATETIME", Target: "findings[].source_extra.last_test_datetime"},
		{Path: qDet + "/LAST_UPDATE_DATETIME", Target: "findings[].source_extra.last_update_datetime"},
		{Path: qDet + "/FIRST_REOPENED_DATETIME", Target: "findings[].source_extra.first_reopened_datetime"},
		{Path: qDet + "/LAST_REOPENED_DATETIME", Target: "findings[].source_extra.last_reopened_datetime"},
		{Path: qDet + "/TIMES_REOPENED", Target: "findings[].source_extra.times_reopened"},
		{Path: qDet + "/SERVICE", Target: "findings[].network.service"},
		{Path: qDet + "/IS_IGNORED", Target: "findings[].source_extra.is_ignored"},
		{Path: qDet + "/IS_DISABLED", Target: "findings[].source_extra.is_disabled"},
		{Path: qDet + "/AFFECT_RUNNING_KERNEL", Target: "findings[].source_extra.affect_running_kernel"},
		{Path: qDet + "/AFFECT_RUNNING_SERVICE", Target: "findings[].source_extra.affect_running_service"},
		{Path: qDet + "/AFFECT_EXPLOITABLE_CONFIG", Target: "findings[].source_extra.affect_exploitable_config"},
		{Path: qDet + "/LAST_PROCESSED_DATETIME", Target: "findings[].source_extra.last_processed_datetime"},
		{Path: qDet + "/QDS", Target: "findings[].scores[] (vendor, source qualys, label = the severity attribute)"},
		{Path: qDet + "/QDS/@severity", Target: "findings[].scores[].label"},
		{Path: qDet + "/QDS_FACTORS", Target: Container},
		{Path: qDet + "/QDS_FACTORS/QDS_FACTOR[*]", Target: "findings[].source_extra.qds_factors"},
		{Path: qDet + "/QDS_FACTORS/QDS_FACTOR[*]/@name", Target: Container},
	},
})
