package importer

var _ = registerSpec(Spec{
	Format:        FormatNuclei,
	Title:         "nuclei JSON lines",
	SourceVersion: "nuclei v3 -jsonl (one result per line) or -json-export (an array of the same objects)",
	Rules: []string{
		"One finding per result, on a domain or ip_address asset named by host, else matched-at, else ip (ids asset-1, asset-2, ... in order of first appearance). A result that names no host is skipped with an issue.",
		"Each line (or array element) is checked on its own: invalid JSON, a value over a limit or a wrong type skips that record with an issue at its line; the other records are imported.",
		"The raw request and response become one http_exchange evidence item (CTIS 1.6), capped (bodies 64 KiB, headers 100 of 8 KiB, the item 256 KiB), with the extracted values (at most 20 of 1 KiB, located in the response body when found there) and the matcher name; the curl command becomes a curl item. Sensitive values (Authorization, Cookie, Set-Cookie, API-key and session headers, sensitive query, form and JSON members, extracted values that look like credentials, and every repetition of them) are marked in the items' sensitive spans, never masked: the receiver masks them.",
		"An http matched-at becomes finding.web (CTIS 1.6): the URL without user info, fragment or query values (names kept, as name=), the method (fuzzing_method, else the request line's) and, for a DAST result, the fuzzed parameter (fuzzing_parameter at fuzzing_position). A URL is never put in location.path, the code-file field.",
	},
	Fields: []Field{
		{Path: "/template-id", Target: "findings[].rule_id, native.vuln_id"},
		{Path: "/template", Target: "findings[].source_extra.template_path"},
		{Path: "/template-path", Target: "findings[].source_extra.template_path"},
		{Path: "/template-url", Target: "findings[].references"},
		{Path: "/template-encoded", Ignored: "the whole template, base64"},
		{Path: "/info", Target: Container},
		{Path: "/info/name", Target: "findings[].title, message"},
		{Path: "/info/severity", Target: "findings[].severity, native.severity"},
		{Path: "/info/description", Target: "findings[].description"},
		{Path: "/info/author", Target: "findings[].source_extra.authors (template authors)"},
		{Path: "/info/author[]", Target: "findings[].source_extra.authors (template authors)"},
		{Path: "/info/tags", Target: "findings[].tags"},
		{Path: "/info/tags[]", Target: "findings[].tags"},
		{Path: "/info/reference", Target: "findings[].references"},
		{Path: "/info/reference[]", Target: "findings[].references"},
		{Path: "/info/remediation", Target: "findings[].remediation.recommendation"},
		{Path: "/info/impact", Target: "findings[].source_extra.impact"},
		{Path: "/info/metadata", Target: "findings[].source_extra.template_metadata"},
		{Path: "/info/metadata/**", Target: "findings[].source_extra.template_metadata"},
		{Path: "/info/classification", Target: Container},
		{Path: "/info/classification/cve-id", Target: "findings[].vulnerability.cve_id, cve_ids, ids"},
		{Path: "/info/classification/cve-id[]", Target: "findings[].vulnerability.cve_id, cve_ids, ids"},
		{Path: "/info/classification/cwe-id", Target: "findings[].vulnerability.cwe_ids"},
		{Path: "/info/classification/cwe-id[]", Target: "findings[].vulnerability.cwe_ids"},
		{Path: "/info/classification/cvss-metrics", Target: "findings[].vulnerability.cvss_vector, scores[].vector"},
		{Path: "/info/classification/cvss-score", Target: "findings[].vulnerability.cvss_score, scores[]"},
		{Path: "/info/classification/epss-score", Target: "findings[].vulnerability.epss_score, scores[] (epss)"},
		{Path: "/info/classification/epss-percentile", Target: "findings[].vulnerability.epss_percentile"},
		{Path: "/info/classification/cpe", Target: "findings[].vulnerability.cpe"},
		{Path: "/type", Target: "findings[].tags (protocol)"},
		{Path: "/host", Target: "assets[] (the host), fingerprint input"},
		{Path: "/port", Target: "findings[].network.port"},
		{Path: "/scheme", Target: "findings[].network.service"},
		{Path: "/url", Ignored: "the target URL; host and matched-at are kept"},
		{Path: "/path", Ignored: "template path on the target; matched-at is kept"},
		{Path: "/matched-at", Target: "findings[].web.url, message (no user info, fragment or query values)"},
		{Path: "/fuzzing_method", Target: "findings[].web.method"},
		{Path: "/fuzzing_parameter", Target: "findings[].web.parameter.name"},
		{Path: "/fuzzing_position", Target: "findings[].web.parameter.location (query, path, header, cookie, body as form, json, multipart)"},
		{Path: "/is_fuzzing_result", Ignored: "a DAST result; fuzzing_parameter says which parameter"},
		{Path: "/ip", Target: "assets[].properties.ip_address, asset (when no host)"},
		{Path: "/timestamp", Target: "findings[].source_extra.timestamp, evidence_items[].captured_at"},
		{Path: "/matcher-name", Target: "findings[].source_extra.matcher_name, evidence_items[http_exchange].match[].matcher"},
		{Path: "/matcher-status", Target: "findings[].confidence (90 when matched, else 70)"},
		{Path: "/extractor-name", Target: "findings[].source_extra.extractor_name"},
		{Path: "/extracted-results", Target: Container},
		{Path: "/extracted-results[]", Target: "findings[].evidence_items[http_exchange].extracted, match (sensitive when credential-like)"},
		{Path: "/curl-command", Target: "findings[].evidence_items[curl].text (sensitive values marked)"},
		{Path: "/request", Target: "findings[].evidence_items[http_exchange].http.request, web.method (sensitive values marked)"},
		{Path: "/response", Target: "findings[].evidence_items[http_exchange].http.response (sensitive values marked)"},
		{Path: "/meta", Ignored: "template variables"},
		{Path: "/meta/**", Ignored: "template variables"},
		{Path: "/matcher-line", Ignored: "line numbers of a file match"},
		{Path: "/matcher-line[]", Ignored: "line numbers of a file match"},
		{Path: "/interaction", Ignored: "out-of-band interaction data: can hold data of the target"},
		{Path: "/interaction/**", Ignored: "out-of-band interaction data: can hold data of the target"},
	},
})
