package importer

const spdxPkg = "/packages[]"

var _ = registerSpec(Spec{
	Format:        FormatSPDX,
	Title:         "SPDX JSON",
	SourceVersion: "SPDX 2.2 and 2.3 JSON",
	Rules: []string{
		"SPDX holds packages, not vulnerabilities: the result is one asset and its dependencies, no findings.",
		"The asset is the described package (documentDescribes, else the DESCRIBES / DESCRIBED_BY relationship of the document): value is its purl, else name@version; type container for a CONTAINER purpose, host for OPERATING-SYSTEM, DEVICE, FIRMWARE, else repository. Without one, a repository asset named after the document holds the dependencies, and an issue says so. A document without packages creates no asset.",
		"Every other package is a dependency: id is its SPDXID (a second package with a used SPDXID is skipped with an issue); licenses are licenseConcluded, else licenseDeclared, never NOASSERTION or NONE.",
		"DEPENDS_ON and CONTAINS (and their inverses DEPENDENCY_OF, CONTAINED_BY) between packages become depends_on; from the described package they make the target a direct dependency. Other relationship types are ignored.",
		"Suppliers and originators are kept only as organization names: a \"Person:\" value, and every e-mail address, is never read. Document creators are kept only when they are tools.",
	},
	Fields: []Field{
		{Path: "/spdxVersion", Target: "metadata.properties.spdx_version (must be SPDX-2.x)"},
		{Path: "/dataLicense", Ignored: "license of the document itself"},
		{Path: "/SPDXID", Target: "the DESCRIBES relationship of the document"},
		{Path: "/name", Target: "metadata.properties.sbom_name, the asset when no package is described"},
		{Path: "/documentNamespace", Target: "metadata.properties.sbom_namespace"},
		{Path: "/comment", Ignored: "free text about the document"},
		{Path: "/creationInfo", Target: Container},
		{Path: "/creationInfo/created", Target: "metadata.properties.sbom_created"},
		{Path: "/creationInfo/creators", Target: Container},
		{Path: "/creationInfo/creators[]", Target: "metadata.properties.sbom_tools (Tool: entries only; persons and organizations are not read)"},
		{Path: "/creationInfo/licenseListVersion", Ignored: "version of the SPDX license list used"},
		{Path: "/creationInfo/comment", Ignored: "free text about the document"},
		{Path: "/externalDocumentRefs", Ignored: "other SPDX documents; only this one is read"},
		{Path: "/externalDocumentRefs[]/**", Ignored: "other SPDX documents; only this one is read"},
		{Path: "/documentDescribes", Target: Container},
		{Path: "/documentDescribes[]", Target: "assets[] (the first described package)"},
		{Path: "/packages", Target: Container},
		{Path: spdxPkg, Target: "dependencies[], assets[] (the described package)"},
		{Path: spdxPkg + "/SPDXID", Target: "dependencies[].id"},
		{Path: spdxPkg + "/name", Target: "dependencies[].name, assets[].name"},
		{Path: spdxPkg + "/versionInfo", Target: "dependencies[].version, assets[].value, assets[].properties.version"},
		{Path: spdxPkg + "/primaryPackagePurpose", Target: "dependencies[].type, assets[].type, assets[].properties.package_purpose"},
		{Path: spdxPkg + "/supplier", Target: "dependencies[].properties.supplier (organizations only)"},
		{Path: spdxPkg + "/originator", Target: "dependencies[].properties.originator (organizations only)"},
		{Path: spdxPkg + "/downloadLocation", Target: "dependencies[].properties.download_location"},
		{Path: spdxPkg + "/homepage", Target: "dependencies[].properties.homepage"},
		{Path: spdxPkg + "/licenseConcluded", Target: "dependencies[].licenses"},
		{Path: spdxPkg + "/licenseDeclared", Target: "dependencies[].licenses (when nothing is concluded)"},
		{Path: spdxPkg + "/licenseInfoFromFiles", Ignored: "licenses found in the package files; the concluded or declared license is kept"},
		{Path: spdxPkg + "/licenseInfoFromFiles[]", Ignored: "licenses found in the package files; the concluded or declared license is kept"},
		{Path: spdxPkg + "/licenseComments", Ignored: "free text about the license"},
		{Path: spdxPkg + "/copyrightText", Ignored: "copyright notice text"},
		{Path: spdxPkg + "/checksums", Target: Container},
		{Path: spdxPkg + "/checksums[]", Target: Container},
		{Path: spdxPkg + "/checksums[]/algorithm", Target: "dependencies[].properties.checksum_<algorithm> (key)"},
		{Path: spdxPkg + "/checksums[]/checksumValue", Target: "dependencies[].properties.checksum_<algorithm>"},
		{Path: spdxPkg + "/externalRefs", Target: Container},
		{Path: spdxPkg + "/externalRefs[]", Target: Container},
		{Path: spdxPkg + "/externalRefs[]/referenceCategory", Target: "selects PERSISTENT-ID refs"},
		{Path: spdxPkg + "/externalRefs[]/referenceType", Target: "selects purl, cpe23Type/cpe22Type, advisory/fix/url/swid, PERSISTENT-ID refs"},
		{Path: spdxPkg + "/externalRefs[]/referenceLocator", Target: "dependencies[].purl (purl), properties.cpe (cpe), properties.security_refs (advisory, fix, url, swid), properties.persistent_id_<type>; assets[].value (purl)"},
		{Path: spdxPkg + "/externalRefs[]/comment", Ignored: "free text about the reference"},
		{Path: spdxPkg + "/releaseDate", Target: "dependencies[].properties.release_date"},
		{Path: spdxPkg + "/builtDate", Target: "dependencies[].properties.built_date"},
		{Path: spdxPkg + "/validUntilDate", Ignored: "end of support date of the package; not a property CTIS defines"},
		{Path: spdxPkg + "/filesAnalyzed", Ignored: "whether the producer looked at the files"},
		{Path: spdxPkg + "/packageFileName", Ignored: "file name of the package archive"},
		{Path: spdxPkg + "/packageVerificationCode/**", Ignored: "digest of the package files; checksums are kept"},
		{Path: spdxPkg + "/hasFiles", Ignored: "files of the package; files are not imported"},
		{Path: spdxPkg + "/hasFiles[]", Ignored: "files of the package; files are not imported"},
		{Path: spdxPkg + "/sourceInfo", Ignored: "free text about the package source"},
		{Path: spdxPkg + "/description", Ignored: "free text about the package"},
		{Path: spdxPkg + "/summary", Ignored: "free text about the package"},
		{Path: spdxPkg + "/comment", Ignored: "free text about the package"},
		{Path: spdxPkg + "/attributionTexts", Ignored: "attribution notices"},
		{Path: spdxPkg + "/attributionTexts[]", Ignored: "attribution notices"},
		{Path: spdxPkg + "/annotations", Ignored: "comments by people; names and text"},
		{Path: spdxPkg + "/annotations[]/**", Ignored: "comments by people; names and text"},
		{Path: "/relationships", Target: Container},
		{Path: "/relationships[]", Target: Container},
		{Path: "/relationships[]/spdxElementId", Target: "dependencies[].depends_on, relationship (the dependent)"},
		{Path: "/relationships[]/relationshipType", Target: "selects DEPENDS_ON, DEPENDENCY_OF, CONTAINS, CONTAINED_BY, DESCRIBES, DESCRIBED_BY"},
		{Path: "/relationships[]/relatedSpdxElement", Target: "dependencies[].depends_on, relationship (the dependency)"},
		{Path: "/relationships[]/comment", Ignored: "free text about the relationship"},
		{Path: "/files", Ignored: "files and their licenses; a package inventory is imported, not a file inventory"},
		{Path: "/files[]/**", Ignored: "files and their licenses; a package inventory is imported, not a file inventory"},
		{Path: "/snippets", Ignored: "snippets of files; not imported"},
		{Path: "/snippets[]/**", Ignored: "snippets of files; not imported"},
		{Path: "/hasExtractedLicensingInfos", Ignored: "texts of non-SPDX licenses"},
		{Path: "/hasExtractedLicensingInfos[]/**", Ignored: "texts of non-SPDX licenses"},
		{Path: "/annotations", Ignored: "comments by people; names and text"},
		{Path: "/annotations[]/**", Ignored: "comments by people; names and text"},
	},
})
