package importer

const (
	grM   = "/matches[]"
	grV   = grM + "/vulnerability"
	grR   = grM + "/relatedVulnerabilities[]"
	grArt = grM + "/artifact"
)

// grypeMeta lists the members a vulnerability and a related vulnerability
// share, under prefix p.
func grypeMeta(p, who string) []Field {
	return []Field{
		{Path: p + "/id", Target: "findings[].rule_id, native.vuln_id, vulnerability.ids[]" + who},
		{Path: p + "/dataSource", Target: "findings[].references (http(s) only)"},
		{Path: p + "/namespace", Target: "findings[].native.family, scores[].source (fallback), source_extra.namespace"},
		{Path: p + "/severity", Target: "findings[].severity, native.severity"},
		{Path: p + "/urls", Target: Container},
		{Path: p + "/urls[]", Target: "findings[].references (http(s) only)"},
		{Path: p + "/description", Target: "findings[].description"},
		{Path: p + "/cvss", Target: Container},
		{Path: p + "/cvss[]", Target: "findings[].scores[] (cvss, one per entry), vulnerability.cvss_* (best)"},
		{Path: p + "/cvss[]/source", Target: "findings[].scores[].source"},
		{Path: p + "/cvss[]/type", Ignored: "Primary or Secondary; the source is kept"},
		{Path: p + "/cvss[]/version", Ignored: "the version is read from the vector"},
		{Path: p + "/cvss[]/vector", Target: "findings[].scores[].vector, version"},
		{Path: p + "/cvss[]/metrics", Target: Container},
		{Path: p + "/cvss[]/metrics/baseScore", Target: "findings[].scores[].value"},
		{Path: p + "/cvss[]/metrics/exploitabilityScore", Ignored: "a sub-score derived from the vector"},
		{Path: p + "/cvss[]/metrics/impactScore", Ignored: "a sub-score derived from the vector"},
		{Path: p + "/cvss[]/vendorMetadata", Ignored: "feed-specific metadata"},
		{Path: p + "/cvss[]/vendorMetadata/**", Ignored: "feed-specific metadata"},
		{Path: p + "/epss", Target: Container},
		{Path: p + "/epss[]", Target: Container},
		{Path: p + "/epss[]/cve", Ignored: "the CVE the EPSS entry is for; it is one of the finding's ids"},
		{Path: p + "/epss[]/epss", Target: "findings[].scores[] (epss), vulnerability.epss_score"},
		{Path: p + "/epss[]/percentile", Target: "findings[].scores[] (epss_percentile), vulnerability.epss_percentile"},
		{Path: p + "/epss[]/date", Target: "findings[].scores[].as_of"},
		{Path: p + "/knownExploited", Target: Container},
		{Path: p + "/knownExploited[]", Target: "findings[].vulnerability.in_cisa_kev, exploit_available"},
		{Path: p + "/knownExploited[]/cve", Ignored: "the CVE of the KEV entry; it is one of the finding's ids"},
		{Path: p + "/knownExploited[]/vendorProject", Target: "findings[].source_extra.kev_vendor_product"},
		{Path: p + "/knownExploited[]/product", Target: "findings[].source_extra.kev_vendor_product"},
		{Path: p + "/knownExploited[]/dateAdded", Target: "findings[].source_extra.kev_date_added"},
		{Path: p + "/knownExploited[]/requiredAction", Target: "findings[].source_extra.kev_required_action"},
		{Path: p + "/knownExploited[]/dueDate", Target: "findings[].source_extra.kev_due_date"},
		{Path: p + "/knownExploited[]/knownRansomwareCampaignUse", Target: "findings[].source_extra.kev_ransomware_use"},
		{Path: p + "/knownExploited[]/notes", Target: "findings[].source_extra.kev_notes"},
		{Path: p + "/knownExploited[]/urls", Target: Container},
		{Path: p + "/knownExploited[]/urls[]", Target: "findings[].references (http(s) only)"},
		{Path: p + "/knownExploited[]/cwes", Target: Container},
		{Path: p + "/knownExploited[]/cwes[]", Target: "findings[].vulnerability.cwe_ids"},
	}
}

var _ = registerSpec(Spec{
	Format:        FormatGrype,
	Title:         "grype JSON output",
	SourceVersion: "grype 0.7x-0.8x `-o json`",
	Rules: []string{
		"One asset for the scanned source: an image is a container asset named by the image reference, a directory or file a repository asset named by its path, an SBOM an unclassified asset; Options.DefaultAsset replaces it.",
		"One finding per match on that asset, with the package, version, PURL and CPE of the artifact; one dependency per artifact.",
		"Severity: the severity word (Critical, High, Medium, Low, Negligible); Unknown falls back to the best CVSS score, else medium with an issue.",
		"Every CVSS entry of the vulnerability and of its related vulnerabilities goes to finding.scores with its source (nvd@nist.gov is nvd); the legacy cvss_* members take the newest version.",
		"The scan configuration in descriptor.configuration (registry settings, paths, credentials) is never read.",
	},
	Fields: append(append([]Field{
		{Path: "/matches", Target: Container},
		{Path: grM, Target: "findings[]"},
		{Path: grV, Target: Container},
		{Path: grV + "/fix", Target: Container},
		{Path: grV + "/fix/versions", Target: Container},
		{Path: grV + "/fix/versions[]", Target: "findings[].vulnerability.fixed_versions, fixed_version, remediation.recommendation"},
		{Path: grV + "/fix/state", Target: "findings[].remediation.fix_available, solution_type, source_extra.fix_state"},
		{Path: grV + "/fix/available*", Ignored: "per-version availability dates; the fixed versions are kept"},
		{Path: grV + "/fix/available*/**", Ignored: "per-version availability dates; the fixed versions are kept"},
		{Path: grV + "/advisories", Target: Container},
		{Path: grV + "/advisories[]", Target: Container},
		{Path: grV + "/advisories[]/id", Target: "findings[].remediation.advisories[].id"},
		{Path: grV + "/advisories[]/link", Target: "findings[].remediation.advisories[].url (http(s) only)"},
		{Path: grV + "/risk", Target: "findings[].scores[] (vendor, label risk, source grype)"},
		{Path: "/matches[]/relatedVulnerabilities", Target: Container},
		{Path: grR, Target: Container},
	}, append(grypeMeta(grV, ""), grypeMeta(grR, " (related)")...)...), []Field{
		{Path: "/matches[]/matchDetails", Target: Container},
		{Path: "/matches[]/matchDetails[]", Target: Container},
		{Path: "/matches[]/matchDetails[]/type", Target: "findings[].source_extra.match_type (first entry)"},
		{Path: "/matches[]/matchDetails[]/matcher", Target: "findings[].source_extra.matcher (first entry)"},
		{Path: "/matches[]/matchDetails[]/fix", Target: Container},
		{Path: "/matches[]/matchDetails[]/fix/suggestedVersion", Target: "findings[].source_extra.suggested_version"},
		{Path: "/matches[]/matchDetails[]/searchedBy", Ignored: "how the matcher searched (matcher internals)"},
		{Path: "/matches[]/matchDetails[]/searchedBy/**", Ignored: "how the matcher searched (matcher internals)"},
		{Path: "/matches[]/matchDetails[]/found", Ignored: "the database record the matcher found (matcher internals)"},
		{Path: "/matches[]/matchDetails[]/found/**", Ignored: "the database record the matcher found (matcher internals)"},
		{Path: grArt, Target: "dependencies[]"},
		{Path: grArt + "/id", Target: "dependencies[].id"},
		{Path: grArt + "/name", Target: "dependencies[].name, findings[].vulnerability.package"},
		{Path: grArt + "/version", Target: "dependencies[].version, findings[].vulnerability.affected_version"},
		{Path: grArt + "/type", Target: "dependencies[].type, ecosystem (fallback)"},
		{Path: grArt + "/locations", Target: Container},
		{Path: grArt + "/locations[]", Target: Container},
		{Path: grArt + "/locations[]/path", Target: "dependencies[].path, findings[].location.path (first location)"},
		{Path: grArt + "/locations[]/layerID", Target: "dependencies[].properties.layer_id (first location)"},
		{Path: grArt + "/locations[]/accessPath", Ignored: "the path through links; path is kept"},
		{Path: grArt + "/locations[]/annotations", Ignored: "evidence annotations of the cataloger"},
		{Path: grArt + "/locations[]/annotations/**", Ignored: "evidence annotations of the cataloger"},
		{Path: grArt + "/language", Target: "dependencies[].ecosystem (fallback), properties.language"},
		{Path: grArt + "/licenses", Target: Container},
		{Path: grArt + "/licenses[]", Target: "dependencies[].licenses"},
		{Path: grArt + "/cpes", Target: Container},
		{Path: grArt + "/cpes[]", Target: "findings[].vulnerability.cpe, dependencies[].properties.cpe (first)"},
		{Path: grArt + "/purl", Target: "findings[].vulnerability.purl, dependencies[].purl, ecosystem"},
		{Path: grArt + "/upstreams", Target: Container},
		{Path: grArt + "/upstreams[]", Target: Container},
		{Path: grArt + "/upstreams[]/name", Target: "dependencies[].properties.upstream (first)"},
		{Path: grArt + "/upstreams[]/version", Target: "dependencies[].properties.upstream (first)"},
		{Path: grArt + "/metadataType", Ignored: "the type of the cataloger metadata below"},
		{Path: grArt + "/metadata", Ignored: "cataloger-specific package metadata"},
		{Path: grArt + "/metadata/**", Ignored: "cataloger-specific package metadata"},
		{Path: "/ignoredMatches", Ignored: "matches the scan's ignore rules suppressed; they are not findings of the scan"},
		{Path: "/ignoredMatches[]", Ignored: "matches the scan's ignore rules suppressed"},
		{Path: "/ignoredMatches[]/**", Ignored: "matches the scan's ignore rules suppressed"},
		{Path: "/source", Target: Container},
		{Path: "/source/type", Target: "assets[].type, properties.source_type"},
		{Path: "/source/target", Target: "assets[].value (a path string, or the object below)"},
		{Path: "/source/target/userInput", Target: "assets[].value (the image reference)"},
		{Path: "/source/target/imageID", Target: "assets[].properties.image_id"},
		{Path: "/source/target/manifestDigest", Target: "assets[].properties.manifest_digest"},
		{Path: "/source/target/tags", Target: Container},
		{Path: "/source/target/tags[]", Target: "assets[].properties.image_tag (first)"},
		{Path: "/source/target/repoDigests", Target: Container},
		{Path: "/source/target/repoDigests[]", Target: "assets[].properties.repo_digest (first)"},
		{Path: "/source/target/architecture", Target: "assets[].properties.architecture"},
		{Path: "/source/target/os", Target: "assets[].properties.os"},
		{Path: "/source/target/path", Target: "assets[].value (a directory or file source)"},
		{Path: "/source/target/mediaType", Ignored: "image manifest media type"},
		{Path: "/source/target/imageSize", Ignored: "image size"},
		{Path: "/source/target/layers*", Ignored: "image layers (digests and sizes)"},
		{Path: "/source/target/layers*/**", Ignored: "image layers (digests and sizes)"},
		{Path: "/source/target/manifest", Ignored: "the raw image manifest (base64)"},
		{Path: "/source/target/config", Ignored: "the raw image configuration (base64; may hold environment values)"},
		{Path: "/source/target/labels", Ignored: "image labels chosen by the image author"},
		{Path: "/source/target/labels/**", Ignored: "image labels chosen by the image author"},
		{Path: "/source/target/variant", Ignored: "platform variant"},
		{Path: "/distro", Target: Container},
		{Path: "/distro/name", Target: "assets[].properties.distro"},
		{Path: "/distro/version", Target: "assets[].properties.distro"},
		{Path: "/distro/idLike", Ignored: "related distribution families"},
		{Path: "/distro/idLike[]", Ignored: "related distribution families"},
		{Path: "/descriptor", Target: Container},
		{Path: "/descriptor/name", Ignored: "always grype; the tool is named by the format"},
		{Path: "/descriptor/version", Target: "tool.version"},
		{Path: "/descriptor/timestamp", Target: "metadata.properties.generated_at"},
		{Path: "/descriptor/db", Target: Container},
		{Path: "/descriptor/db/built", Target: "metadata.properties.grype_db_built"},
		{Path: "/descriptor/db/schemaVersion", Target: "metadata.properties.grype_db_schema"},
		{Path: "/descriptor/db/location", Ignored: "a path on the scanning machine"},
		{Path: "/descriptor/db/checksum", Ignored: "database file checksum"},
		{Path: "/descriptor/db/error", Ignored: "database load error text"},
		{Path: "/descriptor/db/**", Ignored: "database bookkeeping"},
		{Path: "/descriptor/configuration", Ignored: "the scan configuration: registry settings, paths and credentials"},
		{Path: "/descriptor/configuration/**", Ignored: "the scan configuration: registry settings, paths and credentials"},
	}...),
})
