package importer

const (
	osvPkg = "/results[]/packages[]"
	osvRec = osvPkg + "/vulnerabilities[]"
	osvAff = osvRec + "/affected[]"
)

var _ = registerSpec(Spec{
	Format:        FormatOSV,
	Title:         "osv-scanner JSON results (OSV records)",
	SourceVersion: "osv-scanner 1.x and 2.x JSON output; OSV schema 1.0 to 1.7 records",
	Rules: []string{
		"One asset per scanned source (results[].source.path, as a label of at most 255 characters; never opened): type repository, id osv-<path>. Every package of the source is a dependency of it (path = the source label, so a receiver attributes it to that asset).",
		"One finding per package and vulnerability group: a group (groups[]) joins the records of one vulnerability under all its ids; records no group names stand alone. A group whose ids name no record, and a withdrawn record, are skipped with an issue.",
		"Ids: the group ids and aliases and every record id and alias go to vulnerability.ids (typed: CVE, GHSA, OSV databases, vendor); rule_id and native.vuln_id are the first record's id.",
		"Severity: max_severity (the group's highest CVSS base score) banded 9/7/4/0.1; else database_specific.severity (GitHub words, MODERATE is medium); else medium with a note in source_extra. native.severity keeps the source value.",
		"severity[] vectors (record and affected) go to scores as CVSS with the version the vector declares and source ghsa or osv; nothing is computed from a vector. Other severity types are vendor labels.",
		"The affected entry of the package (same name and ecosystem) gives affected_version_range (introduced, fixed, last_affected, limit events as >=, <, <=, <), fixed_versions and the purl (with the installed version); a fix makes the remediation an upgrade.",
		"database_specific and ecosystem_specific objects are kept as compact JSON in source_extra (bounded); GitHub cwe_ids become cwe_ids.",
	},
	Fields: []Field{
		{Path: "/results", Target: Container},
		{Path: "/results[]", Target: Container},
		{Path: "/results[]/source", Target: Container},
		{Path: "/results[]/source/path", Target: "assets[].value, name, id; dependencies[].path"},
		{Path: "/results[]/source/type", Target: "assets[].properties.source_type"},
		{Path: "/results[]/packages", Target: Container},
		{Path: osvPkg, Target: "dependencies[]"},
		{Path: osvPkg + "/package", Target: Container},
		{Path: osvPkg + "/package/name", Target: "dependencies[].name, findings[].vulnerability.package"},
		{Path: osvPkg + "/package/version", Target: "dependencies[].version, findings[].vulnerability.affected_version"},
		{Path: osvPkg + "/package/ecosystem", Target: "dependencies[].ecosystem, findings[].vulnerability.ecosystem"},
		{Path: osvPkg + "/package/purl", Target: "dependencies[].purl, findings[].vulnerability.purl"},
		{Path: osvPkg + "/package/commit", Target: "dependencies[].properties.commit"},
		{Path: osvPkg + "/package/inventory/**", Ignored: "where the scanner found the package on its own disk"},
		{Path: osvPkg + "/dependency_groups", Target: Container},
		{Path: osvPkg + "/dependency_groups[]", Target: "dependencies[].properties.dependency_groups"},
		{Path: osvPkg + "/licenses", Target: Container},
		{Path: osvPkg + "/licenses[]", Target: "dependencies[].licenses"},
		{Path: osvPkg + "/license_violations", Ignored: "license policy result of the scanner run"},
		{Path: osvPkg + "/license_violations[]", Ignored: "license policy result of the scanner run"},
		{Path: osvPkg + "/groups", Target: Container},
		{Path: osvPkg + "/groups[]", Target: "findings[] (one per group)"},
		{Path: osvPkg + "/groups[]/ids", Target: Container},
		{Path: osvPkg + "/groups[]/ids[]", Target: "findings[].vulnerability.ids (and the records of the group)"},
		{Path: osvPkg + "/groups[]/aliases", Target: Container},
		{Path: osvPkg + "/groups[]/aliases[]", Target: "findings[].vulnerability.ids"},
		{Path: osvPkg + "/groups[]/max_severity", Target: "findings[].severity, native.severity, source_extra.max_severity"},
		{Path: osvPkg + "/groups[]/experimentalAnalysis/**", Ignored: "experimental call analysis of the scanner run"},
		{Path: osvPkg + "/vulnerabilities", Target: Container},
		{Path: osvRec, Target: "findings[] (through its group)"},
		{Path: osvRec + "/schema_version", Ignored: "OSV schema version of the record"},
		{Path: osvRec + "/id", Target: "findings[].rule_id, native.vuln_id, vulnerability.ids"},
		{Path: osvRec + "/modified", Target: "findings[].vulnerability.modified_at (latest of the group)"},
		{Path: osvRec + "/published", Target: "findings[].vulnerability.published_at (earliest of the group)"},
		{Path: osvRec + "/withdrawn", Target: "skips the finding (issue)"},
		{Path: osvRec + "/aliases", Target: Container},
		{Path: osvRec + "/aliases[]", Target: "findings[].vulnerability.ids"},
		{Path: osvRec + "/related", Target: Container},
		{Path: osvRec + "/related[]", Target: "findings[].source_extra.related"},
		{Path: osvRec + "/upstream", Target: Container},
		{Path: osvRec + "/upstream[]", Target: "findings[].source_extra.upstream"},
		{Path: osvRec + "/summary", Target: "findings[].title, message, description"},
		{Path: osvRec + "/details", Target: "findings[].description"},
		{Path: osvRec + "/severity", Target: Container},
		{Path: osvRec + "/severity[]", Target: "findings[].scores[]"},
		{Path: osvRec + "/severity[]/type", Target: "findings[].scores[].system (CVSS_V2/V3/V4: cvss; others: vendor, source the type)"},
		{Path: osvRec + "/severity[]/score", Target: "findings[].scores[].vector (cvss), label (others); vulnerability.cvss_vector"},
		{Path: osvRec + "/affected", Target: Container},
		{Path: osvAff, Target: "the entry of this package (same name and ecosystem)"},
		{Path: osvAff + "/package", Target: Container},
		{Path: osvAff + "/package/ecosystem", Target: "selects the entry"},
		{Path: osvAff + "/package/name", Target: "selects the entry"},
		{Path: osvAff + "/package/purl", Target: "findings[].vulnerability.purl (with the installed version)"},
		{Path: osvAff + "/severity", Target: Container},
		{Path: osvAff + "/severity[]", Target: "findings[].scores[]"},
		{Path: osvAff + "/severity[]/type", Target: "findings[].scores[].system"},
		{Path: osvAff + "/severity[]/score", Target: "findings[].scores[].vector or label"},
		{Path: osvAff + "/ranges", Target: Container},
		{Path: osvAff + "/ranges[]", Target: Container},
		{Path: osvAff + "/ranges[]/type", Ignored: "range kind (SEMVER, ECOSYSTEM, GIT); the events are kept as written"},
		{Path: osvAff + "/ranges[]/repo", Ignored: "repository of a GIT range"},
		{Path: osvAff + "/ranges[]/events", Target: Container},
		{Path: osvAff + "/ranges[]/events[]", Target: Container},
		{Path: osvAff + "/ranges[]/events[]/introduced", Target: "findings[].vulnerability.affected_version_range (>=)"},
		{Path: osvAff + "/ranges[]/events[]/fixed", Target: "findings[].vulnerability.affected_version_range (<), fixed_version(s), remediation"},
		{Path: osvAff + "/ranges[]/events[]/last_affected", Target: "findings[].vulnerability.affected_version_range (<=)"},
		{Path: osvAff + "/ranges[]/events[]/limit", Target: "findings[].vulnerability.affected_version_range (<)"},
		{Path: osvAff + "/ranges[]/database_specific/**", Ignored: "database detail of a range"},
		{Path: osvAff + "/versions", Ignored: "every affected version, often thousands; the ranges are kept"},
		{Path: osvAff + "/versions[]", Ignored: "every affected version, often thousands; the ranges are kept"},
		{Path: osvAff + "/ecosystem_specific/**", Target: "findings[].source_extra.ecosystem_specific:<id> (compact JSON)"},
		{Path: osvAff + "/database_specific/**", Target: "findings[].source_extra.affected_database_specific:<id> (compact JSON)"},
		{Path: osvRec + "/references", Target: Container},
		{Path: osvRec + "/references[]", Target: Container},
		{Path: osvRec + "/references[]/type", Target: "ADVISORY: findings[].remediation.advisories"},
		{Path: osvRec + "/references[]/url", Target: "findings[].references, remediation.advisories[].url"},
		{Path: osvRec + "/credits", Ignored: "people and organizations credited; names and contacts"},
		{Path: osvRec + "/credits[]/**", Ignored: "people and organizations credited; names and contacts"},
		{Path: osvRec + "/database_specific/**", Target: "findings[].source_extra.database_specific:<id> (compact JSON); cwe_ids; severity (fallback)"},
		{Path: "/experimental_config/**", Ignored: "scanner run configuration"},
	},
})
