package importer

const (
	ovSt   = "/statements[]"
	ovProd = ovSt + "/products[]"
)

var _ = registerSpec(Spec{
	Format:        FormatOpenVEX,
	Title:         "OpenVEX",
	SourceVersion: "OpenVEX v0.2.0 (the v0.0.1 string forms of vulnerability, products and subcomponents are read too)",
	Rules: []string{
		"An OpenVEX document describes products, not findings: the report has no assets or findings, and Result.VEX holds one statement per OpenVEX statement.",
		"Statuses and justifications are the CTIS VEX vocabulary already. A not_affected statement needs a justification or an impact statement; without either it is skipped with an issue.",
		"Statement text: impact_statement (not_affected) or action_statement (affected), followed by status_notes.",
		"Products: identifiers.purl and identifiers.cpe23 (else cpe22) win; an @id that is a PURL or CPE fills the empty one; any other @id is the product name.",
		"Subcomponents narrow a product: they go to products[].subcomponents, and the statement is about those components inside that product only (a v0.0.1 statement-level subcomponents list narrows every product).",
		"Statement source: author (@id) of the document; as_of: the statement's last_updated or timestamp, else the document's.",
	},
	Fields: []Field{
		{Path: "/@context", Target: "metadata.properties.openvex_context (format check)"},
		{Path: "/@id", Target: "metadata.source_ref, vex[].vex.source"},
		{Path: "/author", Target: "vex[].vex.source, metadata.properties.author"},
		{Path: "/role", Ignored: "the author's role (prose)"},
		{Path: "/timestamp", Target: "vex[].vex.as_of (when the statement has none)"},
		{Path: "/last_updated", Target: "vex[].vex.as_of (when the statement has none)"},
		{Path: "/version", Target: "metadata.properties.document_version"},
		{Path: "/tooling", Target: "metadata.properties.tooling"},
		{Path: "/statements", Target: Container},
		{Path: ovSt, Target: "vex[]"},
		{Path: ovSt + "/@id", Ignored: "statement id; the document id is the source"},
		{Path: ovSt + "/version", Ignored: "statement revision"},
		{Path: ovSt + "/vulnerability", Target: "vex[].vulnerability_ids (v0.0.1 string, or the object below)"},
		{Path: ovSt + "/vulnerability/name", Target: "vex[].vulnerability_ids"},
		{Path: ovSt + "/vulnerability/aliases", Target: Container},
		{Path: ovSt + "/vulnerability/aliases[]", Target: "vex[].vulnerability_ids"},
		{Path: ovSt + "/vulnerability/@id", Ignored: "IRI of the vulnerability record; name and aliases carry the ids"},
		{Path: ovSt + "/vulnerability/description", Ignored: "vulnerability prose; the statement text is kept"},
		{Path: ovSt + "/products", Target: Container},
		{Path: ovProd, Target: "vex[].products[] (v0.0.1 string, or the object below)"},
		{Path: ovProd + "/@id", Target: "vex[].products[].purl, cpe or name"},
		{Path: ovProd + "/identifiers", Target: Container},
		{Path: ovProd + "/identifiers/purl", Target: "vex[].products[].purl"},
		{Path: ovProd + "/identifiers/cpe23", Target: "vex[].products[].cpe"},
		{Path: ovProd + "/identifiers/cpe22", Target: "vex[].products[].cpe (when no cpe23)"},
		{Path: ovProd + "/hashes", Ignored: "artifact hashes; findings are matched on PURL and CPE"},
		{Path: ovProd + "/hashes/*", Ignored: "artifact hashes; findings are matched on PURL and CPE"},
		{Path: ovProd + "/subcomponents", Target: Container},
		{Path: ovProd + "/subcomponents[]", Target: "vex[].products[].subcomponents[] (v0.0.1 string, or the object below)"},
		{Path: ovProd + "/subcomponents[]/@id", Target: "vex[].products[].subcomponents[].purl, cpe or name"},
		{Path: ovProd + "/subcomponents[]/identifiers", Target: Container},
		{Path: ovProd + "/subcomponents[]/identifiers/purl", Target: "vex[].products[].subcomponents[].purl"},
		{Path: ovProd + "/subcomponents[]/identifiers/cpe23", Target: "vex[].products[].subcomponents[].cpe"},
		{Path: ovProd + "/subcomponents[]/identifiers/cpe22", Target: "vex[].products[].subcomponents[].cpe (when no cpe23)"},
		{Path: ovProd + "/subcomponents[]/hashes", Ignored: "artifact hashes; findings are matched on PURL and CPE"},
		{Path: ovProd + "/subcomponents[]/hashes/*", Ignored: "artifact hashes; findings are matched on PURL and CPE"},
		{Path: ovSt + "/subcomponents", Target: Container},
		{Path: ovSt + "/subcomponents[]", Target: "vex[].products[].subcomponents[] (v0.0.1: narrows every product)"},
		{Path: ovSt + "/status", Target: "vex[].vex.status"},
		{Path: ovSt + "/status_notes", Target: "vex[].vex.statement (appended)"},
		{Path: ovSt + "/justification", Target: "vex[].vex.justification, native_justification"},
		{Path: ovSt + "/impact_statement", Target: "vex[].vex.statement (not_affected)"},
		{Path: ovSt + "/action_statement", Target: "vex[].vex.statement (affected)"},
		{Path: ovSt + "/action_statement_timestamp", Ignored: "when the action statement was written; the statement date is kept"},
		{Path: ovSt + "/timestamp", Target: "vex[].vex.as_of (when no last_updated)"},
		{Path: ovSt + "/last_updated", Target: "vex[].vex.as_of"},
		{Path: ovSt + "/supplier", Ignored: "who supplies the product, not who makes the statement"},
	},
})
