package importer

const (
	vuC  = "/scannedCves/*"
	vuCL = "/scannedCves[]"
)

// vulsCVEFields are the members of a scanned CVE, under both forms of
// scannedCves (an object keyed by CVE id, which vuls writes, or a list).
func vulsCVEFields(p string) []Field {
	cc := p + "/cveContents/*[]"
	return []Field{
		{Path: p, Target: "findings[]"},
		{Path: p + "/cveID", Target: "findings[].rule_id, native.vuln_id, vulnerability.ids, cve_id"},
		{Path: p + "/confidences", Target: Container},
		{Path: p + "/confidences[]", Target: Container},
		{Path: p + "/confidences[]/score", Target: "findings[].confidence (the first)"},
		{Path: p + "/confidences[]/detectionMethod", Target: "findings[].source_extra.detection_method"},
		{Path: p + "/affectedPackages", Target: Container},
		{Path: p + "/affectedPackages[]", Target: Container},
		{Path: p + "/affectedPackages[]/name", Target: "findings[].vulnerability.package, purl, affected_version (the first)"},
		{Path: p + "/affectedPackages[]/fixedIn", Target: "findings[].vulnerability.fixed_version, remediation"},
		{Path: p + "/affectedPackages[]/notFixedYet", Target: "findings[].remediation.solution_type no_fix"},
		{Path: p + "/affectedPackages[]/fixState", Target: "findings[].source_extra.fix_state"},
		{Path: p + "/cveContents", Target: Container},
		{Path: p + "/cveContents/*", Target: Container},
		{Path: cc, Target: "findings[] details from the preferred source (nvd, redhat, ubuntu, debian, oracle, amazon, suse, then by name)"},
		{Path: cc + "/type", Ignored: "the content source; the key names it"},
		{Path: cc + "/cveID", Ignored: "duplicate of the CVE id"},
		{Path: cc + "/title", Target: "findings[].title"},
		{Path: cc + "/summary", Target: "findings[].description"},
		{Path: cc + "/cvss3Score", Target: "findings[].scores[] (cvss 3.x, every source), vulnerability.cvss_score"},
		{Path: cc + "/cvss3Vector", Target: "findings[].scores[].vector, vulnerability.cvss_vector"},
		{Path: cc + "/cvss3Severity", Ignored: "label of the cvss3 score"},
		{Path: cc + "/cvss2Score", Target: "findings[].scores[] (cvss 2.0), vulnerability.cvss_score (when no v3/v4)"},
		{Path: cc + "/cvss2Vector", Target: "findings[].scores[].vector"},
		{Path: cc + "/cvss2Severity", Ignored: "label of the cvss2 score"},
		{Path: cc + "/cvss40Score", Target: "findings[].scores[] (cvss 4.0), vulnerability.cvss_score"},
		{Path: cc + "/cvss40Vector", Target: "findings[].scores[].vector"},
		{Path: cc + "/cweIDs", Target: Container},
		{Path: cc + "/cweIDs[]", Target: "findings[].vulnerability.cwe_ids"},
		{Path: cc + "/references", Target: Container},
		{Path: cc + "/references[]", Target: Container},
		{Path: cc + "/references[]/link", Target: "findings[].references"},
		{Path: cc + "/references[]/source", Ignored: "reference source; the link is kept"},
		{Path: cc + "/references[]/refID", Ignored: "reference id; the link is kept"},
		{Path: cc + "/references[]/tags", Ignored: "reference tags"},
		{Path: cc + "/references[]/tags[]", Ignored: "reference tags"},
		{Path: cc + "/published", Target: "findings[].vulnerability.published_at"},
		{Path: cc + "/lastModified", Target: "findings[].vulnerability.modified_at"},
		{Path: cc + "/sourceLink", Target: "findings[].references"},
		{Path: cc + "/optional", Ignored: "source-specific extras"},
		{Path: cc + "/optional/**", Ignored: "source-specific extras"},
		{Path: cc + "/*", Ignored: "other content members (cpes, severity words, mitigations)"},
		{Path: cc + "/*/**", Ignored: "other content members (cpes, severity words, mitigations)"},
		{Path: p + "/alertDict", Ignored: "security alerts (CERT, US-CERT, JPCERT) of the CVE"},
		{Path: p + "/alertDict/**", Ignored: "security alerts (CERT, US-CERT, JPCERT) of the CVE"},
		{Path: p + "/*", Ignored: "other per-CVE data (exploits, metasploit modules, KEV, CTI): vuls enrichment kept out of this mapping"},
		{Path: p + "/*/**", Ignored: "other per-CVE data"},
	}
}

var _ = registerSpec(Spec{
	Format:        FormatVuls,
	Title:         "vuls JSON scan result",
	SourceVersion: "vuls report JSON (jsonVersion 4) of one server",
	Rules: []string{
		"One asset per file: the first scanned IPv4 address (ip_address, with the server name as host name), else the server name (host). A file that names neither imports nothing, with an issue.",
		"One finding per scanned CVE; severity from the preferred CVSS score (v4, else v3, else v2): 9+ critical, 7+ high, 4+ medium, above 0 low, else info.",
		"Packages become dependencies with an OS PURL (deb, rpm, apk, ...) carrying arch and distro.",
	},
	Fields: append(append([]Field{
		{Path: "/jsonVersion", Target: "format check"},
		{Path: "/serverName", Target: "assets[].value or name, findings[].tags"},
		{Path: "/serverUUID", Ignored: "vuls-internal server id"},
		{Path: "/family", Target: "assets[].tags, properties.os_family, dependencies[].ecosystem, purl type"},
		{Path: "/release", Target: "assets[].tags, properties.os_release, purl distro"},
		{Path: "/container", Ignored: "container of a container scan (vuls container mode)"},
		{Path: "/container/**", Ignored: "container of a container scan"},
		{Path: "/runningKernel", Target: Container},
		{Path: "/runningKernel/version", Target: "assets[].properties.kernel_version"},
		{Path: "/runningKernel/release", Target: "assets[].properties.kernel_release"},
		{Path: "/runningKernel/rebootRequired", Target: "assets[].properties.reboot_required"},
		{Path: "/scannedAt", Target: "assets[].properties.scanned_at"},
		{Path: "/scanMode", Ignored: "scan mode (fast, deep)"},
		{Path: "/scannedVersion", Ignored: "vuls version"},
		{Path: "/scannedRevision", Ignored: "vuls revision"},
		{Path: "/scannedBy", Ignored: "the host vuls ran on"},
		{Path: "/scannedVia", Target: "assets[].properties.scanned_via"},
		{Path: "/scannedIpv4Addrs", Target: Container},
		{Path: "/scannedIpv4Addrs[]", Target: "assets[].value (the first)"},
		{Path: "/scannedIpv6Addrs", Target: Container},
		{Path: "/scannedIpv6Addrs[]", Target: "assets[].properties.ipv6_addresses"},
		{Path: "/reportedAt", Ignored: "report time"},
		{Path: "/reportedVersion", Ignored: "vuls version"},
		{Path: "/reportedRevision", Ignored: "vuls revision"},
		{Path: "/reportedBy", Ignored: "the host vuls reported from"},
		{Path: "/errors", Ignored: "scan errors"},
		{Path: "/errors[]", Ignored: "scan errors"},
		{Path: "/warnings", Ignored: "scan warnings"},
		{Path: "/warnings[]", Ignored: "scan warnings"},
		{Path: "/platform", Target: Container},
		{Path: "/platform/name", Target: "assets[].properties.platform"},
		{Path: "/platform/instanceID", Target: "assets[].identity_hints.cloud_resource_id"},
		{Path: "/ipv4Addrs", Ignored: "addresses read on the host; the scanned address is kept"},
		{Path: "/ipv4Addrs[]", Ignored: "addresses read on the host"},
		{Path: "/ipv6Addrs", Ignored: "addresses read on the host"},
		{Path: "/ipv6Addrs[]", Ignored: "addresses read on the host"},
		{Path: "/packages", Target: Container},
		{Path: "/packages/*", Target: "dependencies[]"},
		{Path: "/packages/*/name", Target: "dependencies[].name, purl"},
		{Path: "/packages/*/version", Target: "dependencies[].version, purl"},
		{Path: "/packages/*/release", Target: "dependencies[].version, purl"},
		{Path: "/packages/*/arch", Target: "dependencies[].purl (arch)"},
		{Path: "/packages/*/repository", Ignored: "package repository"},
		{Path: "/packages/*/newVersion", Ignored: "available update; fixed versions come from the CVE"},
		{Path: "/packages/*/newRelease", Ignored: "available update; fixed versions come from the CVE"},
		{Path: "/packages/*/*", Ignored: "other package details (changelog, processes using it)"},
		{Path: "/packages/*/*/**", Ignored: "other package details"},
		{Path: "/srcPackages", Ignored: "source packages; binary packages are kept"},
		{Path: "/srcPackages/**", Ignored: "source packages; binary packages are kept"},
		{Path: "/scannedCves", Target: Container},
	}, vulsCVEFields(vuC)...), vulsCVEFields(vuCL)...),
})
